/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleCaixa;
import control.ControleSecretario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import static java.util.Collections.list;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DatasetUtils;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import util.AtualizadorHorario;

/**
 *
 * @author abner
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    ControleCaixa contCaixa = new ControleCaixa();

    public Dashboard() {
        initComponents();

        AtualizadorHorario ah = new AtualizadorHorario(txtHora, txtDataHora);
        AtualizadorHorario ah2 = new AtualizadorHorario(txtHora1, txtDataHora1);
        ah.mostrarData(true);
        ah2.mostrarData(true);
        Thread thHora = ah;
        Thread thHora2 = ah2;
        thHora.start();
        thHora2.start();

        this.setTitle("SIGAM");
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage(getClass().getResource("/view/images/favicon2.png")));
        this.setExtendedState(MAXIMIZED_BOTH);

        try {
            ImageIcon im = new ImageIcon(ControleSecretario.getLogado().getImagem());
            profileImagePanel.setImage(im.getImage());
            profileImagePanel.repaint();
        } catch (Exception e) {

        }

        renderChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logo1 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        logo2 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        logo3 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        profileImagePanel = new com.hq.swingmaterialdesign.materialdesign.MGradientPanel();
        panToggle = new javax.swing.JPanel();
        toggleHome = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        toggleButtons = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        panGuia = new javax.swing.JPanel();
        panHome = new javax.swing.JPanel();
        panHomeGradient = new com.hq.swingmaterialdesign.materialdesign.MGradientPanel();
        txtHora = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtDataHora = new javax.swing.JLabel();
        panChart = new javax.swing.JPanel();
        btnExit2 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        jButton1 = new javax.swing.JButton();
        panButtons = new javax.swing.JPanel();
        panButtonsGradient = new com.hq.swingmaterialdesign.materialdesign.MGradientPanel();
        txtHora1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtDataHora1 = new javax.swing.JLabel();
        mGradientButton1 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mGradientButton2 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        mGradientButton3 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        jLabel3 = new javax.swing.JLabel();
        mGradientButton4 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mGradientButton7 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        mGradientButton8 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        jLabel6 = new javax.swing.JLabel();
        btnExit = new com.hq.swingmaterialdesign.materialdesign.MButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        sidePanel.setBackground(new java.awt.Color(37, 46, 55));

        logo1.setBorderRadius(10);
        logo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logo1.setEndColor(new java.awt.Color(222, 128, 63));
        logo1.setHoverEndColor(new java.awt.Color(240, 240, 240));
        logo1.setHoverStartColor(new java.awt.Color(240, 240, 240));
        logo1.setStartColor(new java.awt.Color(223, 80, 50));
        logo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logo1ActionPerformed(evt);
            }
        });

        logo2.setBorderRadius(10);
        logo2.setContentAreaFilled(false);
        logo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logo2.setEndColor(new java.awt.Color(220, 138, 68));
        logo2.setHoverEndColor(new java.awt.Color(240, 240, 240));
        logo2.setHoverStartColor(new java.awt.Color(240, 240, 240));
        logo2.setStartColor(new java.awt.Color(223, 95, 52));

        logo3.setBorderRadius(10);
        logo3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logo3.setEndColor(new java.awt.Color(223, 95, 52));
        logo3.setHoverEndColor(new java.awt.Color(240, 240, 240));
        logo3.setHoverStartColor(new java.awt.Color(240, 240, 240));
        logo3.setStartColor(new java.awt.Color(223, 108, 54));

        profileImagePanel.setBackground(new java.awt.Color(37, 46, 55));
        profileImagePanel.setBorderRadius(120);
        profileImagePanel.setFillBackground(false);
        profileImagePanel.setFillImage(true);

        javax.swing.GroupLayout profileImagePanelLayout = new javax.swing.GroupLayout(profileImagePanel);
        profileImagePanel.setLayout(profileImagePanelLayout);
        profileImagePanelLayout.setHorizontalGroup(
            profileImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        profileImagePanelLayout.setVerticalGroup(
            profileImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panToggle.setLayout(new java.awt.GridLayout(2, 1));

        toggleHome.setBorder(null);
        toggleHome.setForeground(new java.awt.Color(255, 255, 255));
        toggleHome.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.HOME));
        toggleHome.setBorderRadius(0);
        toggleHome.setEndColor(new java.awt.Color(37, 46, 55));
        toggleHome.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        toggleHome.setHoverEndColor(new java.awt.Color(37, 46, 55));
        toggleHome.setHoverStartColor(new java.awt.Color(69, 86, 103));
        toggleHome.setIndicatorColor(new java.awt.Color(223, 95, 52));
        toggleHome.setSelectedColor(new java.awt.Color(69, 86, 103));
        toggleHome.setStartColor(new java.awt.Color(37, 46, 55));
        toggleHome.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        toggleHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleHomeActionPerformed(evt);
            }
        });
        panToggle.add(toggleHome);

        toggleButtons.setBorder(null);
        toggleButtons.setForeground(new java.awt.Color(255, 255, 255));
        toggleButtons.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ADD));
        toggleButtons.setBorderRadius(0);
        toggleButtons.setEndColor(new java.awt.Color(37, 46, 55));
        toggleButtons.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        toggleButtons.setHoverEndColor(new java.awt.Color(37, 46, 55));
        toggleButtons.setHoverStartColor(new java.awt.Color(69, 86, 103));
        toggleButtons.setIndicatorColor(new java.awt.Color(223, 95, 52));
        toggleButtons.setSelectedColor(new java.awt.Color(69, 86, 103));
        toggleButtons.setStartColor(new java.awt.Color(37, 46, 55));
        toggleButtons.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        toggleButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonsActionPerformed(evt);
            }
        });
        panToggle.add(toggleButtons);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(profileImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(panToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(profileImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panGuia.setLayout(new java.awt.CardLayout());

        panHomeGradient.setBorderRadius(0);
        panHomeGradient.setEndColor(new java.awt.Color(37, 46, 55));
        panHomeGradient.setStartColor(new java.awt.Color(50, 60, 69));

        txtHora.setFont(new java.awt.Font("Nunito SemiBold", 0, 48)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtDataHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDataHora.setForeground(new java.awt.Color(255, 255, 255));
        txtDataHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        panChart.setBackground(new Color(0,0,0,0));
        panChart.setLayout(new java.awt.BorderLayout());

        btnExit2.setBackground(new java.awt.Color(37, 46, 55));
        btnExit2.setBorder(null);
        btnExit2.setForeground(new java.awt.Color(247, 183, 51));
        btnExit2.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnExit2.setBorderRadius(0);
        btnExit2.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnExit2.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExit2MouseExited(evt);
            }
        });
        btnExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit2ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panHomeGradientLayout = new javax.swing.GroupLayout(panHomeGradient);
        panHomeGradient.setLayout(panHomeGradientLayout);
        panHomeGradientLayout.setHorizontalGroup(
            panHomeGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHomeGradientLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panHomeGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panHomeGradientLayout.createSequentialGroup()
                        .addGap(0, 674, Short.MAX_VALUE)
                        .addGroup(panHomeGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panHomeGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHomeGradientLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panHomeGradientLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panHomeGradientLayout.setVerticalGroup(
            panHomeGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHomeGradientLayout.createSequentialGroup()
                .addComponent(btnExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panChart, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout panHomeLayout = new javax.swing.GroupLayout(panHome);
        panHome.setLayout(panHomeLayout);
        panHomeLayout.setHorizontalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panHomeGradient, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE))
        );
        panHomeLayout.setVerticalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panHomeGradient, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))
        );

        panGuia.add(panHome, "card4");

        panButtonsGradient.setBorderRadius(0);
        panButtonsGradient.setEndColor(new java.awt.Color(37, 46, 55));
        panButtonsGradient.setStartColor(new java.awt.Color(50, 60, 69));

        txtHora1.setFont(new java.awt.Font("Nunito SemiBold", 0, 48)); // NOI18N
        txtHora1.setForeground(new java.awt.Color(255, 255, 255));
        txtHora1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtDataHora1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDataHora1.setForeground(new java.awt.Color(255, 255, 255));
        txtDataHora1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        mGradientButton1.setBackground(new Color(0,0,0,0));
        mGradientButton1.setBorder(null);
        mGradientButton1.setForeground(new java.awt.Color(255, 255, 255));
        mGradientButton1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.PERSON_ADD));
        mGradientButton1.setBorderRadius(40);
        mGradientButton1.setEndColor(new java.awt.Color(247, 183, 51));
        mGradientButton1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(40f));
        mGradientButton1.setStartColor(new java.awt.Color(252, 74, 26));
        mGradientButton1.setType(com.hq.swingmaterialdesign.materialdesign.MGradientButton.Type.FLAT);
        mGradientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALUNOS");

        jLabel2.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SECRETÁRIOS");

        mGradientButton2.setBackground(new Color(0,0,0,0));
        mGradientButton2.setBorder(null);
        mGradientButton2.setForeground(new java.awt.Color(255, 255, 255));
        mGradientButton2.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.PERSON_ADD));
        mGradientButton2.setBorderRadius(40);
        mGradientButton2.setEndColor(new java.awt.Color(247, 183, 51));
        mGradientButton2.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(40f));
        mGradientButton2.setStartColor(new java.awt.Color(252, 74, 26));
        mGradientButton2.setType(com.hq.swingmaterialdesign.materialdesign.MGradientButton.Type.FLAT);
        mGradientButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton2ActionPerformed(evt);
            }
        });

        mGradientButton3.setBackground(new Color(0,0,0,0));
        mGradientButton3.setBorder(null);
        mGradientButton3.setForeground(new java.awt.Color(255, 255, 255));
        mGradientButton3.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.PERSON_ADD));
        mGradientButton3.setBorderRadius(40);
        mGradientButton3.setEndColor(new java.awt.Color(247, 183, 51));
        mGradientButton3.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(40f));
        mGradientButton3.setStartColor(new java.awt.Color(252, 74, 26));
        mGradientButton3.setType(com.hq.swingmaterialdesign.materialdesign.MGradientButton.Type.FLAT);
        mGradientButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TREINADORES");

        mGradientButton4.setBackground(new Color(0,0,0,0));
        mGradientButton4.setBorder(null);
        mGradientButton4.setForeground(new java.awt.Color(255, 255, 255));
        mGradientButton4.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.PERSON_ADD));
        mGradientButton4.setBorderRadius(40);
        mGradientButton4.setEndColor(new java.awt.Color(247, 183, 51));
        mGradientButton4.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(40f));
        mGradientButton4.setStartColor(new java.awt.Color(252, 74, 26));
        mGradientButton4.setType(com.hq.swingmaterialdesign.materialdesign.MGradientButton.Type.FLAT);
        mGradientButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CAIXA");

        jLabel5.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DESPESAS");

        mGradientButton7.setBackground(new Color(0,0,0,0));
        mGradientButton7.setBorder(null);
        mGradientButton7.setForeground(new java.awt.Color(255, 255, 255));
        mGradientButton7.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.PERSON_ADD));
        mGradientButton7.setBorderRadius(40);
        mGradientButton7.setEndColor(new java.awt.Color(247, 183, 51));
        mGradientButton7.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(40f));
        mGradientButton7.setStartColor(new java.awt.Color(252, 74, 26));
        mGradientButton7.setType(com.hq.swingmaterialdesign.materialdesign.MGradientButton.Type.FLAT);
        mGradientButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton7ActionPerformed(evt);
            }
        });

        mGradientButton8.setBackground(new Color(0,0,0,0));
        mGradientButton8.setBorder(null);
        mGradientButton8.setForeground(new java.awt.Color(255, 255, 255));
        mGradientButton8.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.PERSON_ADD));
        mGradientButton8.setBorderRadius(40);
        mGradientButton8.setEndColor(new java.awt.Color(247, 183, 51));
        mGradientButton8.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(40f));
        mGradientButton8.setStartColor(new java.awt.Color(252, 74, 26));
        mGradientButton8.setType(com.hq.swingmaterialdesign.materialdesign.MGradientButton.Type.FLAT);
        mGradientButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton8ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PAGAMENTOS");

        btnExit.setBackground(new java.awt.Color(37, 46, 55));
        btnExit.setBorder(null);
        btnExit.setForeground(new java.awt.Color(247, 183, 51));
        btnExit.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnExit.setBorderRadius(0);
        btnExit.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnExit.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panButtonsGradientLayout = new javax.swing.GroupLayout(panButtonsGradient);
        panButtonsGradient.setLayout(panButtonsGradientLayout);
        panButtonsGradientLayout.setHorizontalGroup(
            panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonsGradientLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                            .addComponent(mGradientButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)))
                    .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                            .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52))))
                .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                            .addComponent(mGradientButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)))
                    .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                            .addComponent(mGradientButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46))))
                .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panButtonsGradientLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(mGradientButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panButtonsGradientLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(mGradientButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDataHora1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panButtonsGradientLayout.setVerticalGroup(
            panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                        .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                                .addComponent(mGradientButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                                .addComponent(mGradientButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(38, 38, 38)
                        .addGroup(panButtonsGradientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                                .addComponent(mGradientButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                                .addComponent(mGradientButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsGradientLayout.createSequentialGroup()
                        .addComponent(mGradientButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(txtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout panButtonsLayout = new javax.swing.GroupLayout(panButtons);
        panButtons.setLayout(panButtonsLayout);
        panButtonsLayout.setHorizontalGroup(
            panButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panButtonsGradient, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panButtonsLayout.setVerticalGroup(
            panButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panButtonsGradient, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panGuia.add(panButtons, "card4");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1098, Short.MAX_VALUE))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(panGuia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panGuia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logo1ActionPerformed

    private void toggleHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleHomeActionPerformed
        panButtons.setVisible(false);
        panHome.setVisible(true);
    }//GEN-LAST:event_toggleHomeActionPerformed

    private void mGradientButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton4ActionPerformed
        FormCaixa tela = new FormCaixa(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_mGradientButton4ActionPerformed

    private void toggleButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonsActionPerformed
        panButtons.setVisible(true);
        panHome.setVisible(false);
    }//GEN-LAST:event_toggleButtonsActionPerformed

    private void mGradientButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton2ActionPerformed
        FormSecretario form = new FormSecretario(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_mGradientButton2ActionPerformed

    private void mGradientButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton3ActionPerformed
        FormTreinador form = new FormTreinador(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_mGradientButton3ActionPerformed

    private void mGradientButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton1ActionPerformed
        FormAluno form = new FormAluno(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_mGradientButton1ActionPerformed

    private void mGradientButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton7ActionPerformed
        FormDespesas form = new FormDespesas(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_mGradientButton7ActionPerformed

    private void mGradientButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton8ActionPerformed
        FormPagamento form = new FormPagamento(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_mGradientButton8ActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit2MouseEntered

    private void btnExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit2MouseExited

    private void btnExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String caminho = new File("src/relatorios/Balanco.jrxml").getAbsolutePath();
        JasperReport relatorio;
        
        JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(contCaixa.findAll(), false);
        JasperPrint print;
        try {
    
            relatorio = JasperCompileManager.compileReport(caminho);
            print = JasperFillManager.fillReport(relatorio,null , dados);
            JasperViewer viw = new JasperViewer(print, false);
            viw.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private XYDataset createDataset() {
        XYSeriesCollection dataset = new XYSeriesCollection();

        XYSeries s = new XYSeries("Y = X + 2");
        s.add(2, 4);
        s.add(8, 10);
        s.add(10, 12);
        s.add(13, 15);
        s.add(17, 19);
        s.add(18, 20);
        s.add(21, 23);

        dataset.addSeries(s);

        return dataset;
    }

    private void renderChart() {
        XYDataset ds = createDataset();
        JFreeChart chart = ChartFactory.createXYLineChart("FLUXO MONETÁRIO", "x-axis", "y-axis", ds, PlotOrientation.VERTICAL, true, true, false);
        chart.setBackgroundPaint(new Color(0, 0, 0, 0));
        chart.setBorderVisible(false);
        chart.setBorderPaint(new Color(0, 0, 0, 0));
        chart.getXYPlot().setBackgroundPaint(new Color(0, 0, 0, 0));

        chart.getXYPlot().setDomainGridlinePaint(new Color(0, 0, 0, 0));
        chart.getXYPlot().setDomainGridlinesVisible(false);
        chart.getXYPlot().setOutlinePaint(new Color(0, 0, 0, 0));

        ChartPanel cp = new ChartPanel(chart);
        cp.setBackground(new Color(0, 0, 0, 0));
        panChart.add(cp, BorderLayout.CENTER);
        panChart.validate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnExit;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnExit2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton logo1;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton logo2;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton logo3;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton1;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton2;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton3;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton4;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton7;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton8;
    private javax.swing.JPanel panButtons;
    private com.hq.swingmaterialdesign.materialdesign.MGradientPanel panButtonsGradient;
    private javax.swing.JPanel panChart;
    private javax.swing.JPanel panGuia;
    private javax.swing.JPanel panHome;
    private com.hq.swingmaterialdesign.materialdesign.MGradientPanel panHomeGradient;
    private javax.swing.JPanel panToggle;
    private com.hq.swingmaterialdesign.materialdesign.MGradientPanel profileImagePanel;
    private javax.swing.JPanel sidePanel;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton toggleButtons;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton toggleHome;
    private javax.swing.JLabel txtDataHora;
    private javax.swing.JLabel txtDataHora1;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtHora1;
    // End of variables declaration//GEN-END:variables
}
