/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author abner
 */
public class FormSecretario extends javax.swing.JDialog {

    /**
     * Creates new form FormSecretário
     */
    public FormSecretario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mToggleButton1 = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mToggleButton2 = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mToggleButton3 = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        cardPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        mTextField1 = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mButton3 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        formPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mButton4 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        mTextField2 = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        mButton2 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        mButton5 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        profileImagePanel = new com.hq.swingmaterialdesign.materialdesign.MGradientPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(37, 46, 55));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SECRETÁRIO");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 230, 40));

        mToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        mToggleButton1.setText("Excluir");
        mToggleButton1.setEndColor(new java.awt.Color(37, 46, 55));
        mToggleButton1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        mToggleButton1.setHoverEndColor(new java.awt.Color(37, 46, 55));
        mToggleButton1.setHoverStartColor(new java.awt.Color(0, 153, 153));
        mToggleButton1.setSelectedColor(new java.awt.Color(0, 153, 153));
        mToggleButton1.setStartColor(new java.awt.Color(37, 46, 55));
        mToggleButton1.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        mToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mToggleButton1ActionPerformed(evt);
            }
        });
        sidePanel.add(mToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        mToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        mToggleButton2.setText("Adicionar");
        mToggleButton2.setEndColor(new java.awt.Color(37, 46, 55));
        mToggleButton2.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        mToggleButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mToggleButton2.setHoverEndColor(new java.awt.Color(37, 46, 55));
        mToggleButton2.setHoverStartColor(new java.awt.Color(0, 153, 153));
        mToggleButton2.setSelectedColor(new java.awt.Color(0, 153, 153));
        mToggleButton2.setStartColor(new java.awt.Color(37, 46, 55));
        mToggleButton2.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        mToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mToggleButton2ActionPerformed(evt);
            }
        });
        sidePanel.add(mToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        mToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        mToggleButton3.setText("Alterar");
        mToggleButton3.setEndColor(new java.awt.Color(37, 46, 55));
        mToggleButton3.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        mToggleButton3.setHoverEndColor(new java.awt.Color(37, 46, 55));
        mToggleButton3.setHoverStartColor(new java.awt.Color(0, 153, 153));
        mToggleButton3.setSelectedColor(new java.awt.Color(0, 153, 153));
        mToggleButton3.setStartColor(new java.awt.Color(37, 46, 55));
        mToggleButton3.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        sidePanel.add(mToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 460));

        cardPanel.setLayout(new java.awt.CardLayout());

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchPanel.setBackground(new java.awt.Color(50, 60, 69));

        mTextField1.setBackground(new java.awt.Color(50, 60, 69));
        mTextField1.setForeground(new java.awt.Color(240, 240, 240));
        mTextField1.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        mTextField1.setLabel("Pesquisar");
        mTextField1.setSelectionColor(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(mTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        dataPanel.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 100));

        jScrollPane1.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        dataPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 580, 270));

        mButton3.setBackground(new java.awt.Color(255, 255, 255));
        mButton3.setForeground(new java.awt.Color(153, 153, 153));
        mButton3.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton3.setBorderRadius(0);
        mButton3.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton3.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton3MouseExited(evt);
            }
        });
        mButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton3ActionPerformed(evt);
            }
        });
        dataPanel.add(mButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 40));

        cardPanel.add(dataPanel, "card2");

        formPanel.setBackground(new java.awt.Color(255, 255, 255));

        mButton4.setForeground(new java.awt.Color(153, 153, 153));
        mButton4.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton4.setBorderRadius(0);
        mButton4.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton4.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton4MouseExited(evt);
            }
        });
        mButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mTextField2.setLabel("Nome");

        mButton2.setBorder(null);
        mButton2.setText("CANCELAR");
        mButton2.setBorderRadius(50);
        mButton2.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        mButton2.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        mButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton2ActionPerformed(evt);
            }
        });

        mButton5.setBackground(new java.awt.Color(51, 51, 51));
        mButton5.setBorder(null);
        mButton5.setText("Confirmar");
        mButton5.setBorderRadius(50);
        mButton5.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        mButton5.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        mButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton5ActionPerformed(evt);
            }
        });

        profileImagePanel.setBackground(new java.awt.Color(255, 255, 255));
        profileImagePanel.setBorderRadius(120);
        profileImagePanel.setFillBackground(false);
        profileImagePanel.setFillImage(true);
        profileImagePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileImagePanelMouseEntered(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/profileImageHover.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout profileImagePanelLayout = new javax.swing.GroupLayout(profileImagePanel);
        profileImagePanel.setLayout(profileImagePanelLayout);
        profileImagePanelLayout.setHorizontalGroup(
            profileImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profileImagePanelLayout.setVerticalGroup(
            profileImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanelLayout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(mButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(profileImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(mTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanelLayout.createSequentialGroup()
                    .addContainerGap(428, Short.MAX_VALUE)
                    .addComponent(mButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(mButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanelLayout.createSequentialGroup()
                    .addContainerGap(398, Short.MAX_VALUE)
                    .addComponent(mButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)))
        );

        cardPanel.add(formPanel, "card3");

        bg.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 620, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mToggleButton1ActionPerformed

    private void mButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton3MouseEntered
        mButton3.setForeground(new java.awt.Color(50,60,69));
    }//GEN-LAST:event_mButton3MouseEntered

    private void mButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton3MouseExited
        mButton3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_mButton3MouseExited

    private void mButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton3ActionPerformed

    private void mButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseEntered
        mButton4.setForeground(new java.awt.Color(50,60,69));
    }//GEN-LAST:event_mButton4MouseEntered

    private void mButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseExited
        mButton4.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_mButton4MouseExited

    private void mButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton4ActionPerformed

    private void mToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mToggleButton2ActionPerformed
        dataPanel.setVisible(false);
        formPanel.setVisible(true);
    }//GEN-LAST:event_mToggleButton2ActionPerformed

    private void mButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton2ActionPerformed
        mToggleButton2.unselect();
        dataPanel.setVisible(true);
        formPanel.setVisible(false);
    }//GEN-LAST:event_mButton2ActionPerformed

    private void mButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mButton5ActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseExited

    private void profileImagePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileImagePanelMouseEntered
        jLabel2.setVisible(true);
    }//GEN-LAST:event_profileImagePanelMouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Selecione a imagem de perfil");
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        FileNameExtensionFilter ext = new FileNameExtensionFilter("Imagem", "png", "jpg", "bmp");
        
        jfc.setFileFilter(ext);
        
        int r = jfc.showOpenDialog(this);
        
        if (r == JFileChooser.APPROVE_OPTION){
            File file = jfc.getSelectedFile();
            Image image = null;
            try {
                image = ImageIO.read(file);
            } catch (IOException ex) {
                System.out.println("//////////DEURUIM NA IMAGEM TRATAR DEPOIS COM AVISO NA TELA");
            } finally {
                System.out.println(file.getAbsolutePath());
                profileImagePanel.setImage(image);
                profileImagePanel.repaint();
                this.repaint();
            }
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormSecretario dialog = new FormSecretario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton2;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton3;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton4;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton5;
    private com.hq.swingmaterialdesign.materialdesign.MTextField mTextField1;
    private com.hq.swingmaterialdesign.materialdesign.MTextField mTextField2;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mToggleButton1;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mToggleButton2;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mToggleButton3;
    private com.hq.swingmaterialdesign.materialdesign.MGradientPanel profileImagePanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
