/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleAluno;
import control.ControleAtividade;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Atividade;
import org.eclipse.persistence.exceptions.DatabaseException;
import util.Conversoes;
import util.LimitText;

/**
 *
 * @author abner
 */
public class FormAtividade extends javax.swing.JDialog {

    private int xMouse, yMouse;
    private Atividade p = new Atividade();
    private ControleAtividade cp = new ControleAtividade();
    private ArrayList<Atividade> listaPesquisa = new ArrayList();
    private Atividade selecionado;
    private int menuSelection = 0;

    public FormAtividade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        this.setLocationRelativeTo(null);
       
        warningPanelForm.setVisible(false);
        warningPanelData.setVisible(false);
    }

    private void atualizaTabela() {
        new Thread() {
            @Override
            public void run() {
                listaPesquisa.clear();
                listaPesquisa.addAll(cp.findByDescricao(txtPesquisa.getText()));
                DefaultTableModel dtm = (DefaultTableModel) tableAtividade.getModel();
                dtm.setNumRows(0);
                for (Atividade  s : listaPesquisa) {
                    dtm.addRow(new Object[]{s.getCodigo(), s.getDescricao(), s.getMusculo().equals("")? "-" : s.getMusculo(), s.getEquipamentos().equals("")? "-" : s.getEquipamentos()});
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        excludeBtn = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        addBtn = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        changeBtn = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        cardPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        warningPanelData = new javax.swing.JPanel();
        btnMessage = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningData = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        txtPesquisa = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        mGradientButton1 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        btnExit = new com.hq.swingmaterialdesign.materialdesign.MButton();
        tablePanel = new javax.swing.JScrollPane();
        tableAtividade = new javax.swing.JTable();
        formPanel = new javax.swing.JPanel();
        warningPanelForm = new javax.swing.JPanel();
        btnError = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningForm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mButton4 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtEquipamentos = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        botCancelar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botConfirmar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtDescricao = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtMusculos = new com.hq.swingmaterialdesign.materialdesign.MTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bgMouseReleased(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(37, 46, 55));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATIVIDADE");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 230, 40));

        excludeBtn.setBorder(null);
        excludeBtn.setForeground(new java.awt.Color(255, 255, 255));
        excludeBtn.setText("Excluir");
        excludeBtn.setEndColor(new java.awt.Color(37, 46, 55));
        excludeBtn.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        excludeBtn.setHoverEndColor(new java.awt.Color(37, 46, 55));
        excludeBtn.setHoverStartColor(new java.awt.Color(0, 153, 153));
        excludeBtn.setSelectedColor(new java.awt.Color(0, 153, 153));
        excludeBtn.setStartColor(new java.awt.Color(37, 46, 55));
        excludeBtn.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        excludeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excludeBtnActionPerformed(evt);
            }
        });
        sidePanel.add(excludeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        addBtn.setBorder(null);
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Adicionar");
        addBtn.setEndColor(new java.awt.Color(37, 46, 55));
        addBtn.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        addBtn.setHoverEndColor(new java.awt.Color(37, 46, 55));
        addBtn.setHoverStartColor(new java.awt.Color(0, 153, 153));
        addBtn.setSelectedColor(new java.awt.Color(0, 153, 153));
        addBtn.setStartColor(new java.awt.Color(37, 46, 55));
        addBtn.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        sidePanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        changeBtn.setBorder(null);
        changeBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeBtn.setText("Alterar");
        changeBtn.setEndColor(new java.awt.Color(37, 46, 55));
        changeBtn.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        changeBtn.setHoverEndColor(new java.awt.Color(37, 46, 55));
        changeBtn.setHoverStartColor(new java.awt.Color(0, 153, 153));
        changeBtn.setSelectedColor(new java.awt.Color(0, 153, 153));
        changeBtn.setStartColor(new java.awt.Color(37, 46, 55));
        changeBtn.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });
        sidePanel.add(changeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 670));

        cardPanel.setLayout(new java.awt.CardLayout());

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelData.setBackground(new java.awt.Color(0, 153, 0));

        btnMessage.setBackground(new java.awt.Color(0, 153, 0));
        btnMessage.setBorder(null);
        btnMessage.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnMessage.setBorderRadius(0);
        btnMessage.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnMessage.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageActionPerformed(evt);
            }
        });

        labelWarningData.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningData.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningData.setText("Cadastro efetuado com sucesso.");

        javax.swing.GroupLayout warningPanelDataLayout = new javax.swing.GroupLayout(warningPanelData);
        warningPanelData.setLayout(warningPanelDataLayout);
        warningPanelDataLayout.setHorizontalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelDataLayout.createSequentialGroup()
                .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelDataLayout.setVerticalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataPanel.add(warningPanelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        searchPanel.setBackground(new java.awt.Color(50, 60, 69));

        txtPesquisa.setBackground(new java.awt.Color(50, 60, 69));
        txtPesquisa.setForeground(new java.awt.Color(240, 240, 240));
        txtPesquisa.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        txtPesquisa.setLabel("Pesquisar");
        txtPesquisa.setSelectionColor(new java.awt.Color(0, 153, 153));

        mGradientButton1.setForeground(new java.awt.Color(204, 204, 204));
        mGradientButton1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.SEARCH));
        mGradientButton1.setBorderRadius(58);
        mGradientButton1.setEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(26f));
        mGradientButton1.setHoverEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setHoverStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseExited(evt);
            }
        });
        mGradientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        dataPanel.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 100));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(null);
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
        btnExit.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnExit.setBorderRadius(0);
        btnExit.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnExit.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        dataPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 50, 40));

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablePanel.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tablePanel.setHorizontalScrollBar(null);

        tableAtividade.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableAtividade.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tableAtividade.setForeground(new java.awt.Color(72, 72, 72));
        tableAtividade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Musculo", "Equipamentos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAtividade.setGridColor(new java.awt.Color(255, 255, 255));
        tableAtividade.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableAtividade.setRowHeight(30);
        tableAtividade.setSelectionBackground(new java.awt.Color(205, 205, 205));
        tablePanel.setViewportView(tableAtividade);
        if (tableAtividade.getColumnModel().getColumnCount() > 0) {
            tableAtividade.getColumnModel().getColumn(0).setResizable(false);
            tableAtividade.getColumnModel().getColumn(1).setResizable(false);
            tableAtividade.getColumnModel().getColumn(2).setResizable(false);
            tableAtividade.getColumnModel().getColumn(3).setResizable(false);
        }
        tableAtividade.getTableHeader().setFont(new java.awt.Font("Nunito Bold", 0, 14));

        dataPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 670, 390));

        cardPanel.add(dataPanel, "card2");

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelForm.setBackground(new java.awt.Color(255, 51, 51));

        btnError.setBackground(new java.awt.Color(255, 51, 51));
        btnError.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnError.setBorderRadius(0);
        btnError.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnError.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorActionPerformed(evt);
            }
        });

        labelWarningForm.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningForm.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningForm.setText("Preencha os campos corretamente.");

        javax.swing.GroupLayout warningPanelFormLayout = new javax.swing.GroupLayout(warningPanelForm);
        warningPanelForm.setLayout(warningPanelFormLayout);
        warningPanelFormLayout.setHorizontalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelFormLayout.createSequentialGroup()
                .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelFormLayout.setVerticalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanel.add(warningPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        mButton4.setBorder(null);
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
        mButton4.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton4.setBorderRadius(0);
        mButton4.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton4.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton4MouseExited(evt);
            }
        });
        mButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        txtEquipamentos.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtEquipamentos.setLabel("Equipamento");
        txtEquipamentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEquipamentosFocusGained(evt);
            }
        });
        txtEquipamentos.setDocument(new LimitText(100));
        formPanel.add(txtEquipamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 503, 51));

        botCancelar.setBorder(null);
        botCancelar.setText("CANCELAR");
        botCancelar.setBorderRadius(50);
        botCancelar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botCancelar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        formPanel.add(botCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 514, 180, 50));

        botConfirmar.setBackground(new java.awt.Color(51, 51, 51));
        botConfirmar.setBorder(null);
        botConfirmar.setText("Confirmar");
        botConfirmar.setBorderRadius(50);
        botConfirmar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botConfirmar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConfirmarActionPerformed(evt);
            }
        });
        formPanel.add(botConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 514, 180, 50));

        txtDescricao.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtDescricao.setLabel("Descrição");
        txtDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescricaoFocusGained(evt);
            }
        });
        txtEquipamentos.setDocument(new LimitText(50));
        formPanel.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 503, 51));

        txtMusculos.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtMusculos.setLabel("Músculos");
        txtMusculos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMusculosFocusGained(evt);
            }
        });
        txtEquipamentos.setDocument(new LimitText(50));
        formPanel.add(txtMusculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 503, 50));

        cardPanel.add(formPanel, "card3");

        bg.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 710, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excludeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excludeBtnActionPerformed
        int linha = tableAtividade.getSelectedRow();
        int codigo;
        Atividade sExcluir = null;
        if (menuSelection == 0) {
            if (linha != -1) {
                menuSelection = 3;
                int colunas = tableAtividade.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableAtividade.getColumnName(x).equals("Código")) {
                        codigo = (int) tableAtividade.getValueAt(linha, x);
                        sExcluir = cp.findByCodigo(codigo);

                    }
                }
                if (sExcluir != null) {
                    int op = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir " + sExcluir.getDescricao()+ "?");
                    if (op == 0) {
                        try {
                            cp.delete(sExcluir);
                            DefaultTableModel dtm = (DefaultTableModel) tableAtividade.getModel();
                            dtm.removeRow(linha);
                            warningPanelData.setVisible(true);
                            warningPanelData.setBackground(new Color(0, 153, 0));
                            btnMessage.setBackground(new Color(0, 153, 0));
                            labelWarningData.setText("Excluído com sucesso!");
                            menuSelection = 0;

                        } catch (Exception e) {
                            warningPanelData.setVisible(true);
                            warningPanelData.setBackground(new Color(255, 51, 51));
                            btnMessage.setBackground(new Color(255, 51, 51));
                            labelWarningData.setText("Esta atividade possui registros vinculados.\nNão foi possível realizar a exclusão!");
                            menuSelection=0;
                            excludeBtn.unselect();
                        }
                    }

                }

            } else {
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                labelWarningData.setText("Selecione uma atividade.");
            }
        } else {
               if (menuSelection == 1) {
                addBtn.select();
                excludeBtn.unselect();
            } else {
                changeBtn.select();
                excludeBtn.unselect();
            }
        }
    }//GEN-LAST:event_excludeBtnActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseEntered
        mButton4.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_mButton4MouseEntered

    private void mButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseExited
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_mButton4MouseExited

    private void mButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton4ActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (menuSelection == 0) {
            menuSelection = 1;
            dataPanel.setVisible(false);
            formPanel.setVisible(true);
            selecionado = null;
            limparCampos();
        } else {
            if (menuSelection == 1) {
                addBtn.select();
                changeBtn.unselect();
            } else {
                changeBtn.select();
                addBtn.unselect();
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
        addBtn.unselect();
        changeBtn.unselect();
        menuSelection = 0;
        dataPanel.setVisible(true);
        formPanel.setVisible(false);
        warningPanelData.setVisible(false);
        warningPanelForm.setVisible(false);
        makeAllBlack();
        limparCampos();
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConfirmarActionPerformed
       
        Color errorColor = new Color(255, 0, 0);
        boolean flag = false;
        String message = "";
       

        if (txtDescricao.getText().equals("")) {
            txtDescricao.setForeground(errorColor);
            flag = true;
        }
       
        
       
        this.repaint();

        if (flag) {
            message = "Descricao obrigatória";

        }
        
       

        if (!flag ) {
            p.setDescricao(txtDescricao.getText());
            p.setEquipamentos(txtEquipamentos.getText());
            p.setMusculo(txtMusculos.getText());
            if (selecionado == null) {
                try {

                    cp.persist(p);
                    message = "Cadastro efetuado com sucesso.";
                    warningPanelData.setBackground(new Color(0, 153, 0));
                    btnMessage.setBackground(new Color(0, 153, 0));
                    warningPanelData.setVisible(true);
                    limparCampos();
                } catch (DatabaseException ex) {
                    message = "Atividade já cadastrada.";
                    warningPanelData.setBackground(new Color(255, 51, 51));
                    btnMessage.setBackground(new Color(255, 51, 51));
                    labelWarningData.setText(message);
                    warningPanelData.setVisible(true);
                }
            } else {
                p.setCodigo(selecionado.getCodigo());
                cp.alter(p);
                message = "Alteração efetuada com sucesso.";
                labelWarningData.setText(message);
                warningPanelData.setBackground(new Color(0, 153, 0));
                btnMessage.setBackground(new Color(0, 153, 0));
                warningPanelData.setVisible(true);
                limparCampos();
            }
            labelWarningData.setText(message);
            menuSelection = 0;
            addBtn.unselect();
            changeBtn.unselect();
            dataPanel.setVisible(true);
            formPanel.setVisible(false);
            warningPanelData.setVisible(true);
            //timer

            // view panel aviso, setColor aviso (danger/success) -> flag , setText(message)
        } else {

            labelWarningForm.setText(message);
            warningPanelForm.setVisible(true);
            warningPanelForm.setBackground(new Color(255, 51, 51));
            btnError.setBackground(new Color(255, 51, 51));

        }
    }//GEN-LAST:event_botConfirmarActionPerformed

    private void makeAllBlack() {
        txtEquipamentos.setForeground(Color.black);
        txtDescricao.setForeground(Color.black);
        txtMusculos.setForeground(Color.black);
        
        
    }

    private void limparCampos() {
        txtEquipamentos.setText("");
        txtMusculos.setText("");
        txtDescricao.setText("");
        
       

       

    }
    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        if (menuSelection == 0) {
            int linha = tableAtividade.getSelectedRow();
            int codigo;
            if (linha != -1) {
                menuSelection = 2;
                int colunas = tableAtividade.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableAtividade.getColumnName(x).equals("Código")) {
                        codigo = (int) tableAtividade.getValueAt(linha, x);
                        selecionado = cp.findByCodigo(codigo);
                        setAtividade();
                        dataPanel.setVisible(false);
                        formPanel.setVisible(true);
                    }
                }

            } else {
                changeBtn.unselect();
                labelWarningData.setText("Selecione uma atividade.");
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                menuSelection=0;
                //timer
            }
        } else {
            if (menuSelection == 1) {
                addBtn.select();
                changeBtn.unselect();
            } else {
                changeBtn.select();
                addBtn.unselect();
            }
        }

    }//GEN-LAST:event_changeBtnActionPerformed

    private void mGradientButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton1ActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_mGradientButton1ActionPerformed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseReleased
        try {
            setOpacity((float) 1);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseReleased

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
        try {
            setOpacity((float) 0.9);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseDragged

    private void mGradientButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseEntered
        mGradientButton1.setForeground(Color.white);
    }//GEN-LAST:event_mGradientButton1MouseEntered

    private void mGradientButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseExited
        mGradientButton1.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_mGradientButton1MouseExited

    private void txtEquipamentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEquipamentosFocusGained
        txtEquipamentos.setForeground(Color.black);
    }//GEN-LAST:event_txtEquipamentosFocusGained

    private void btnErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorActionPerformed
        warningPanelForm.setVisible(false);
    }//GEN-LAST:event_btnErrorActionPerformed

    private void btnMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageActionPerformed
        warningPanelData.setVisible(false);
    }//GEN-LAST:event_btnMessageActionPerformed

    private void txtDescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoFocusGained

    private void txtMusculosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMusculosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMusculosFocusGained

    private void setAtividade() {
        
        txtEquipamentos.setText(selecionado.getEquipamentos());
        txtMusculos.setText(selecionado.getMusculo());
        txtDescricao.setText(selecionado.getDescricao());
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormAtividade dialog = new FormAtividade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton addBtn;
    private javax.swing.JPanel bg;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelar;
    private com.hq.swingmaterialdesign.materialdesign.MButton botConfirmar;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnError;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnExit;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnMessage;
    private javax.swing.JPanel cardPanel;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton changeBtn;
    private javax.swing.JPanel dataPanel;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton excludeBtn;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelWarningData;
    private javax.swing.JLabel labelWarningForm;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton4;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tableAtividade;
    private javax.swing.JScrollPane tablePanel;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtDescricao;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtEquipamentos;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtMusculos;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtPesquisa;
    private javax.swing.JPanel warningPanelData;
    private javax.swing.JPanel warningPanelForm;
    // End of variables declaration//GEN-END:variables
}
