/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleCaixa;
import control.ControleDespesa;
import control.ControleSecretario;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

import model.Despesa;
import util.Conversoes;

/**
 *
 * @author abner
 */
public class FormDespesas extends javax.swing.JDialog {

    private int xMouse, yMouse;
    private Despesa p = new Despesa();
    private ControleDespesa cp = new ControleDespesa();
    private File file;
    private ArrayList<Despesa> listaPesquisa = new ArrayList();
    private Despesa selecionado;
    private int menuSelection = 0;
    private Color errorColor = new Color(255, 0, 0);
    private Color branco = new Color(240, 240, 240);

    public FormDespesas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        this.setLocationRelativeTo(null);

        warningPanelForm.setVisible(false);
        warningPanelData.setVisible(false);
        warningPanelForm1.setVisible(false);
    }

    private void atualizaTabela() {
        new Thread() {
            @Override
            public void run() {
                listaPesquisa.clear();
                if (!txtData1.getText().equals("  /  /    ") || !txtData1.getText().equals("  /  /    ")) {
                    listaPesquisa.addAll(cp.findByDatas(txtData1.getText(), txtData2.getText()));
                    DefaultTableModel dtm = (DefaultTableModel) tableDespesas.getModel();
                    dtm.setNumRows(0);
                    for (Despesa s : listaPesquisa) {
                        dtm.addRow(new Object[]{s.getCodigo(),
                            s.getDescricao(),
                            Conversoes.getDateFormatedToString(s.getVencimento()),
                            s.getPagamento() != null ? Conversoes.getDateFormatedToString(s.getPagamento()) : "não pago", s.getTipo()});
                    }
                } else {
                    warningPanelData.setBackground(new Color(255, 51, 51));
                    btnMessage.setBackground(new Color(255, 51, 51));
                    labelWarningData.setText("Digite a data de inicio e fim da pesquisa");
                    warningPanelData.setVisible(true);

                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAdicionar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnVisualizar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnPagar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        cardPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        warningPanelData = new javax.swing.JPanel();
        btnMessage = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningData = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        mGradientButton1 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        txtData1 = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtData2 = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        btnExit = new com.hq.swingmaterialdesign.materialdesign.MButton();
        tablePanel = new javax.swing.JScrollPane();
        tableDespesas = new javax.swing.JTable();
        formPanelAdicionar = new javax.swing.JPanel();
        warningPanelForm = new javax.swing.JPanel();
        btnError = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningForm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mButton4 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botCancelar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botConfirmar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtVencimento = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtDescricao = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtValor = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        comboTipo = new com.hq.swingmaterialdesign.materialdesign.MComboBox();
        formPanelPagar = new javax.swing.JPanel();
        warningPanelForm1 = new javax.swing.JPanel();
        btnError1 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningForm1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mButton5 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botCancelarFechamento = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botConfirmarFechamento = new com.hq.swingmaterialdesign.materialdesign.MButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelDataPagamento = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        labelDataVencimento = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bgMouseReleased(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(37, 46, 55));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DESPESAS");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 230, 40));

        btnAdicionar.setBorder(null);
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setEndColor(new java.awt.Color(37, 46, 55));
        btnAdicionar.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAdicionar.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnAdicionar.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnAdicionar.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnAdicionar.setStartColor(new java.awt.Color(37, 46, 55));
        btnAdicionar.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        sidePanel.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        btnVisualizar.setBorder(null);
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setText("vISUALIZAR");
        btnVisualizar.setEndColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnVisualizar.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnVisualizar.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnVisualizar.setStartColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        sidePanel.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        btnPagar.setBorder(null);
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("Pagar");
        btnPagar.setEndColor(new java.awt.Color(37, 46, 55));
        btnPagar.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnPagar.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnPagar.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnPagar.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnPagar.setStartColor(new java.awt.Color(37, 46, 55));
        btnPagar.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        sidePanel.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 670));

        cardPanel.setLayout(new java.awt.CardLayout());

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelData.setBackground(new java.awt.Color(0, 153, 0));

        btnMessage.setBackground(new java.awt.Color(0, 153, 0));
        btnMessage.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnMessage.setBorderRadius(0);
        btnMessage.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnMessage.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageActionPerformed(evt);
            }
        });

        labelWarningData.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningData.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningData.setText("Cadastro efetuado com sucesso.");

        javax.swing.GroupLayout warningPanelDataLayout = new javax.swing.GroupLayout(warningPanelData);
        warningPanelData.setLayout(warningPanelDataLayout);
        warningPanelDataLayout.setHorizontalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelDataLayout.createSequentialGroup()
                .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelDataLayout.setVerticalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataPanel.add(warningPanelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        searchPanel.setBackground(new java.awt.Color(50, 60, 69));

        mGradientButton1.setForeground(new java.awt.Color(204, 204, 204));
        mGradientButton1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.SEARCH));
        mGradientButton1.setBorderRadius(58);
        mGradientButton1.setEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(26f));
        mGradientButton1.setHoverEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setHoverStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseExited(evt);
            }
        });
        mGradientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton1ActionPerformed(evt);
            }
        });

        txtData1.setBackground(new java.awt.Color(50, 60, 69));
        txtData1.setForeground(new java.awt.Color(240, 240, 240));
        txtData1.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtData1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData1.setLabel("Data Inicial");
        txtData1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtData1FocusGained(evt);
            }
        });

        txtData2.setBackground(new java.awt.Color(50, 60, 69));
        txtData2.setForeground(new java.awt.Color(240, 240, 240));
        txtData2.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtData2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData2.setLabel("Data Final");
        txtData2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtData2FocusGained(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        dataPanel.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 100));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(null);
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
        btnExit.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnExit.setBorderRadius(0);
        btnExit.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnExit.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        dataPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 50, 40));

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablePanel.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tablePanel.setHorizontalScrollBar(null);

        tableDespesas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableDespesas.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tableDespesas.setForeground(new java.awt.Color(72, 72, 72));
        tableDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descricao", "Data Vencimento", "Data Pagamento", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDespesas.setGridColor(new java.awt.Color(255, 255, 255));
        tableDespesas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableDespesas.setRowHeight(30);
        tableDespesas.setSelectionBackground(new java.awt.Color(205, 205, 205));
        tablePanel.setViewportView(tableDespesas);
        if (tableDespesas.getColumnModel().getColumnCount() > 0) {
            tableDespesas.getColumnModel().getColumn(0).setResizable(false);
            tableDespesas.getColumnModel().getColumn(1).setResizable(false);
            tableDespesas.getColumnModel().getColumn(2).setResizable(false);
            tableDespesas.getColumnModel().getColumn(3).setResizable(false);
            tableDespesas.getColumnModel().getColumn(4).setResizable(false);
        }
        tableDespesas.getTableHeader().setFont(new java.awt.Font("Nunito Bold", 0, 14));

        dataPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 670, 390));

        cardPanel.add(dataPanel, "card2");

        formPanelAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        formPanelAdicionar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelForm.setBackground(new java.awt.Color(255, 51, 51));

        btnError.setBackground(new java.awt.Color(255, 51, 51));
        btnError.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnError.setBorderRadius(0);
        btnError.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnError.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorActionPerformed(evt);
            }
        });

        labelWarningForm.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningForm.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningForm.setText("Preencha os campos corretamente.");

        javax.swing.GroupLayout warningPanelFormLayout = new javax.swing.GroupLayout(warningPanelForm);
        warningPanelForm.setLayout(warningPanelFormLayout);
        warningPanelFormLayout.setHorizontalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelFormLayout.createSequentialGroup()
                .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelFormLayout.setVerticalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelAdicionar.add(warningPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        mButton4.setBorder(null);
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
        mButton4.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton4.setBorderRadius(0);
        mButton4.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton4.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton4MouseExited(evt);
            }
        });
        mButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelAdicionar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        botCancelar.setBorder(null);
        botCancelar.setText("CANCELAR");
        botCancelar.setBorderRadius(50);
        botCancelar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botCancelar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        formPanelAdicionar.add(botCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 514, 180, 50));

        botConfirmar.setBackground(new java.awt.Color(51, 51, 51));
        botConfirmar.setBorder(null);
        botConfirmar.setText("Confirmar");
        botConfirmar.setBorderRadius(50);
        botConfirmar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botConfirmar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConfirmarActionPerformed(evt);
            }
        });
        formPanelAdicionar.add(botConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 514, 180, 50));

        try {
            txtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtVencimento.setLabel("Data de Vencimento");
        formPanelAdicionar.add(txtVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 350, 60));

        txtDescricao.setLabel("Descrição");
        formPanelAdicionar.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 350, 60));

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValor.setLabel("Valor");
        formPanelAdicionar.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 230, 60));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adicional", "Fixa" }));
        formPanelAdicionar.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 350, 50));

        cardPanel.add(formPanelAdicionar, "card3");

        formPanelPagar.setBackground(new java.awt.Color(255, 255, 255));
        formPanelPagar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelForm1.setBackground(new java.awt.Color(255, 51, 51));

        btnError1.setBackground(new java.awt.Color(255, 51, 51));
        btnError1.setBorder(null);
        btnError1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnError1.setBorderRadius(0);
        btnError1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnError1.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnError1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnError1ActionPerformed(evt);
            }
        });

        labelWarningForm1.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningForm1.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningForm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningForm1.setText("Preencha os campos corretamente.");

        javax.swing.GroupLayout warningPanelForm1Layout = new javax.swing.GroupLayout(warningPanelForm1);
        warningPanelForm1.setLayout(warningPanelForm1Layout);
        warningPanelForm1Layout.setHorizontalGroup(
            warningPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelForm1Layout.createSequentialGroup()
                .addComponent(labelWarningForm1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnError1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelForm1Layout.setVerticalGroup(
            warningPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningForm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnError1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelPagar.add(warningPanelForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        jPanel2.setBorder(null);

        mButton5.setForeground(new java.awt.Color(153, 153, 153));
        mButton5.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton5.setBorderRadius(0);
        mButton5.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton5.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton5MouseExited(evt);
            }
        });
        mButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelPagar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        botCancelarFechamento.setBorder(null);
        botCancelarFechamento.setText("CANCELAR");
        botCancelarFechamento.setBorderRadius(50);
        botCancelarFechamento.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botCancelarFechamento.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelarFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarFechamentoActionPerformed(evt);
            }
        });
        formPanelPagar.add(botCancelarFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 514, 180, 50));

        botConfirmarFechamento.setBackground(new java.awt.Color(51, 51, 51));
        botConfirmarFechamento.setBorder(null);
        botConfirmarFechamento.setText("Confirmar");
        botConfirmarFechamento.setBorderRadius(50);
        botConfirmarFechamento.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botConfirmarFechamento.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botConfirmarFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConfirmarFechamentoActionPerformed(evt);
            }
        });
        formPanelPagar.add(botConfirmarFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 514, 180, 50));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel5.setText("Data Pagamento");
        formPanelPagar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel7.setText("Descrição");
        formPanelPagar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        labelDataPagamento.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelDataPagamento.setText("jLabel5");
        formPanelPagar.add(labelDataPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 180, -1));

        labelDescricao.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelDescricao.setText("jLabel7");
        formPanelPagar.add(labelDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 240, -1));
        formPanelPagar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 340, 10));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel8.setText("Data Vencimento");
        formPanelPagar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));
        formPanelPagar.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 340, 10));
        formPanelPagar.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 340, 10));

        labelDataVencimento.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelDataVencimento.setText("jLabel10");
        formPanelPagar.add(labelDataVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 150, -1));

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel10.setText("Valor");
        formPanelPagar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        labelValor.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelValor.setText("jLabel5");
        formPanelPagar.add(labelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 190, -1));
        formPanelPagar.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 340, 10));

        cardPanel.add(formPanelPagar, "card4");

        bg.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 710, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed
    private void voltar() {
        menuSelection = 0;
        btnAdicionar.unselect();;
        btnPagar.unselect();;
        btnVisualizar.unselect();
        limparCampos();
        makeAllBlack();
        dataPanel.setVisible(true);
        formPanelAdicionar.setVisible(false);
        formPanelPagar.setVisible(false);
        atualizaTabela();
    }
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        
        if (menuSelection == 0) {
            if (ControleCaixa.getCaixa() != null) {
                p = new Despesa();
                menuSelection = 1;
                selecionado =null;
                this.repaint();
                dataPanel.setVisible(false);
                formPanelAdicionar.setVisible(true);
                selecionado = null;
            } else {
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                labelWarningData.setText("Abra um caixa!");
                warningPanelData.setVisible(true);
                voltar();
                
            }

        } else {
            if (menuSelection == 2) {
                btnPagar.select();
                btnAdicionar.unselect();
            } else if (menuSelection == 3) {
                btnVisualizar.select();
                btnAdicionar.unselect();
            }
        }


    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void makeAllBlack() {
        txtValor.setForeground(Color.black);
        txtDescricao.setForeground(Color.black);
        txtVencimento.setForeground(Color.black);

    }

    private void limparCampos() {
        txtValor.setText("");
        txtDescricao.setText("");
        txtVencimento.setText("");
    }
    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        if (menuSelection == 0) {
            int linha = tableDespesas.getSelectedRow();
            int codigo;
            if (linha != -1) {
                menuSelection = 3;
                int colunas = tableDespesas.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableDespesas.getColumnName(x).equals("Código")) {
                        codigo = (int) tableDespesas.getValueAt(linha, x);
                        selecionado = cp.findByCodigo(codigo);
                        setDespesa();
                        dataPanel.setVisible(false);
                        formPanelAdicionar.setVisible(true);
                    }
                }

            } else {
                
                labelWarningData.setText("Selecione uma despesa.");
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                voltar();
                //timer
            }
        } else {
            if (menuSelection == 1) {
                btnAdicionar.select();
                btnVisualizar.unselect();
            } else if (menuSelection == 2) {
                btnPagar.select();
                btnVisualizar.unselect();
            }
        }

    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void mGradientButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton1ActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_mGradientButton1ActionPerformed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseReleased
        try {
            setOpacity((float) 1);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseReleased

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
        try {
            setOpacity((float) 0.9);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseDragged

    private void mGradientButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseEntered
        mGradientButton1.setForeground(Color.white);
    }//GEN-LAST:event_mGradientButton1MouseEntered

    private void mGradientButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseExited
        mGradientButton1.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_mGradientButton1MouseExited

    private void btnMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageActionPerformed
        warningPanelData.setVisible(false);
    }//GEN-LAST:event_btnMessageActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed

        if (menuSelection == 0) {
            if (ControleCaixa.getCaixa() != null) {
                int linha = tableDespesas.getSelectedRow();
                int codigo;
                if (linha != -1) {
                    menuSelection = 2;
                    int colunas = tableDespesas.getColumnCount();
                    for (int x = 0; x < colunas; x++) {
                        if (tableDespesas.getColumnName(x).equals("Código")) {
                            codigo = (int) tableDespesas.getValueAt(linha, x);
                            selecionado = cp.findByCodigo(codigo);
                            if (selecionado.getCaixa() == null) {
                                setDespesa();
                                dataPanel.setVisible(false);
                                formPanelPagar.setVisible(true);
                            } else {
                                labelWarningData.setText("Despesa já paga");
                                warningPanelData.setVisible(true);
                                warningPanelData.setBackground(new Color(255, 51, 51));
                                btnMessage.setBackground(new Color(255, 51, 51));
                                voltar();
                            }
                        }
                    }

                } else {
                    
                    labelWarningData.setText("Selecione uma despesa.");
                    warningPanelData.setVisible(true);
                    warningPanelData.setBackground(new Color(255, 51, 51));
                    btnMessage.setBackground(new Color(255, 51, 51));
                    voltar();

                    //timer
                }
            } else {
                
                labelWarningData.setText("Abra um caixa.");
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                voltar();
            }
        } else {
            if (menuSelection == 1) {
                btnAdicionar.select();
                btnPagar.unselect();
            } else if (menuSelection == 3) {
                btnVisualizar.select();
                btnPagar.unselect();
            }
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnError1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnError1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnError1ActionPerformed

    private void mButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mButton5MouseEntered

    private void mButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_mButton5MouseExited

    private void mButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_mButton5ActionPerformed

    private void botCancelarFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarFechamentoActionPerformed
        
        warningPanelData.setVisible(false);
        warningPanelForm1.setVisible(false);
       voltar();
    }//GEN-LAST:event_botCancelarFechamentoActionPerformed

    private void botConfirmarFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConfirmarFechamentoActionPerformed

        String message = "";

        p = selecionado;
        p.setCaixa(ControleCaixa.getCaixa());
        p.setPagamento(new Date());
        cp.alter(p);
        message = "Cadastro efetuado com sucesso.";
        warningPanelData.setBackground(new Color(0, 153, 0));
        btnMessage.setBackground(new Color(0, 153, 0));
        labelWarningData.setText(message);
        warningPanelData.setVisible(true);
        atualizaTabela();
        voltar();


    }//GEN-LAST:event_botConfirmarFechamentoActionPerformed

    private void txtData1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtData1FocusGained
        txtData1.setForeground(branco);
        if (txtData1.getText().equals("  /  /    "))
            txtData1.setCaretPosition(0);
    }//GEN-LAST:event_txtData1FocusGained

    private void txtData2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtData2FocusGained
        txtData2.setForeground(branco);
        if (txtData2.getText().equals("  /  /    "))
            txtData2.setCaretPosition(0);
    }//GEN-LAST:event_txtData2FocusGained

    private void botConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConfirmarActionPerformed

        boolean flag = false;
        String message = "";

        if (txtValor.getText().equals("")) {
            txtValor.setForeground(errorColor);
            flag = true;
        }
        if (txtDescricao.getText().equals("")) {
            txtDescricao.setForeground(errorColor);
            flag = true;
        }
        if (txtVencimento.getText().equals("  /  /    ")) {
            txtVencimento.setForeground(errorColor);
            flag = true;
        }

        this.repaint();
        if (flag) {
            message = "Preencha todos os campos corretamente.";
        }
        if (!flag) {
            p.setTipo(comboTipo.getSelectedItem().toString());
            p.setValor(Double.parseDouble(txtValor.getText().replace(',', '.')));
            p.setDescricao(txtDescricao.getText());
            p.setVencimento(Conversoes.getDateOfString(txtVencimento.getText()));
            cp.persist(p);
            message = "Cadastro efetuado com sucesso.";
            warningPanelData.setBackground(new Color(0, 153, 0));
            btnMessage.setBackground(new Color(0, 153, 0));
            labelWarningData.setText(message);
            warningPanelData.setVisible(true);
            
            voltar();

        } else {

            labelWarningForm.setText(message);
            warningPanelForm.setVisible(true);
            warningPanelForm.setBackground(new Color(255, 51, 51));
            btnError.setBackground(new Color(255, 51, 51));

        }
    }//GEN-LAST:event_botConfirmarActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
       
        warningPanelData.setVisible(false);
        warningPanelForm.setVisible(false);
        voltar();
    }//GEN-LAST:event_botCancelarActionPerformed

    private void mButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton4ActionPerformed

    private void mButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseExited
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_mButton4MouseExited

    private void mButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseEntered
        mButton4.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_mButton4MouseEntered

    private void btnErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorActionPerformed
        warningPanelForm.setVisible(false);
    }//GEN-LAST:event_btnErrorActionPerformed

    private void setDespesa() {
        labelValor.setText(Double.toString(selecionado.getValor()));
        labelDataVencimento.setText(Conversoes.getDateFormatedToString(selecionado.getVencimento()));
        labelDataPagamento.setText(Conversoes.getDateFormatedToString(new Date()));
        labelDescricao.setText(selecionado.getDescricao());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormDespesas dialog = new FormDespesas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelar;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelarFechamento;
    private com.hq.swingmaterialdesign.materialdesign.MButton botConfirmar;
    private com.hq.swingmaterialdesign.materialdesign.MButton botConfirmarFechamento;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnAdicionar;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnError;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnError1;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnExit;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnMessage;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnPagar;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnVisualizar;
    private javax.swing.JPanel cardPanel;
    private com.hq.swingmaterialdesign.materialdesign.MComboBox comboTipo;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel formPanelAdicionar;
    private javax.swing.JPanel formPanelPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labelDataPagamento;
    private javax.swing.JLabel labelDataVencimento;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelWarningData;
    private javax.swing.JLabel labelWarningForm;
    private javax.swing.JLabel labelWarningForm1;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton4;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton5;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tableDespesas;
    private javax.swing.JScrollPane tablePanel;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtData1;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtData2;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtDescricao;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtValor;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtVencimento;
    private javax.swing.JPanel warningPanelData;
    private javax.swing.JPanel warningPanelForm;
    private javax.swing.JPanel warningPanelForm1;
    // End of variables declaration//GEN-END:variables
}
