/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.hq.swingmaterialdesign.materialdesign.MFormattedTextField;
import control.ControleAluno;
import control.ControleAtividade;
import control.ControleCaixa;
import control.ControleFicha;
import control.ControleSecretario;
import java.awt.Color;
import java.io.File;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.persistence.NoResultException;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Atividade;
import model.Caixa;
import model.Ficha;
import model.Itemdeatividade;
import util.Conversoes;

/**
 *
 * @author abner
 */
public class FormFicha extends javax.swing.JDialog {

    private int xMouse, yMouse;
    private Ficha ficha = new Ficha();
    private ControleAluno contAluno = new ControleAluno();
    private ArrayList<Aluno> listaPesquisa = new ArrayList();
    private Aluno selecionado;
    private Color errorColor = new Color(255, 0, 0);
    private Color branco = new Color(240, 240, 240);
    private ControleFicha contFicha = new ControleFicha();
    private ArrayList<Itemdeatividade> listaItens = new ArrayList();
    private ArrayList<Atividade> listaAtivides = new ArrayList<>();
    private ControleAtividade contAti = new ControleAtividade();

    public FormFicha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        warningPanelForm.setVisible(false);
        warningPanelData.setVisible(false);

    }

    private void atualizaTabela() {
        new Thread() {
            @Override
            public void run() {
                listaPesquisa.clear();
                String ultima = "-";
                String proxima = "-";

                listaPesquisa.addAll(contAluno.findByNome(txtPesquisa.getText()));
                DefaultTableModel dtm = (DefaultTableModel) tableAlunos.getModel();
                dtm.setNumRows(0);

                for (Aluno s : listaPesquisa) {
                    try {
                        ultima = Conversoes.getDateToString(contFicha.findByAlunoLast(s).getDataAv());
                        proxima = Conversoes.getDateToString(contFicha.findByAlunoLast(s).getProxAv());
                    } catch (NoResultException e) {

                    }
                    dtm.addRow(new Object[]{s.getCodigo(),
                        s.getNome(),
                        ultima, proxima, s.getDataUltima() == null ? "-" : Conversoes.getDateToString(s.getDataUltima())});
                }

            }
        }.start();
    }

    private void setAluno() {
        if (selecionado.getImagem() != null) {
            if (selecionado.getImagem().length > 0) {
                ImageIcon im = new ImageIcon(selecionado.getImagem());
                profileImagePanel1.setImage(im.getImage());
                profileImagePanel1.repaint();
            }
        }
        txtProximaAv.setText(Conversoes.getDateToString(Conversoes.somaData(new Date(), 90)));
        labelNome.setText(selecionado.getNome());
        try {
            labelIdade.setText(Conversoes.calculaIdade(selecionado.getDataNasc()).toString());
        } catch (ParseException ex) {
            labelIdade.setText("--");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNovaFicha = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnUltimaFicha = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnPorPeriodo = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        txtData1 = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtData2 = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        warningPanelData = new javax.swing.JPanel();
        btnMessage = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningData = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        mGradientButton1 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        txtPesquisa = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        btnExit = new com.hq.swingmaterialdesign.materialdesign.MButton();
        tablePanel = new javax.swing.JScrollPane();
        tableAlunos = new javax.swing.JTable();
        formPanelAbrir = new javax.swing.JPanel();
        warningPanelForm = new javax.swing.JPanel();
        btnError = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningForm = new javax.swing.JLabel();
        botConfirmar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botCancelar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        profileImagePanel1 = new com.hq.swingmaterialdesign.materialdesign.MGradientPanel();
        labelNome = new javax.swing.JLabel();
        labelIdade = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelItens = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        mButton4 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtProximaAv = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        txtPesquisaAtividade = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        botAddAtiv = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAtividades = new javax.swing.JTable();
        txtDuracao = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtSeries = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtRepeticoes = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        botPesqAtividade = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        jPanel4 = new javax.swing.JPanel();
        txtPanturrilhaEsq = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtAltura = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtCintura = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtAbdomen = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtQuadril = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtPeso = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtBicepsEsq = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtAntebracoEsq = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtCoxaEsq = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtBicepsDir = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtAntebracoDir = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtCoxaDir = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtPanturrilhaDir = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bgMouseReleased(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(37, 46, 55));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FICHA DE TREINO");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 230, 40));

        btnNovaFicha.setBorder(null);
        btnNovaFicha.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaFicha.setText("NOVA FICHA");
        btnNovaFicha.setEndColor(new java.awt.Color(37, 46, 55));
        btnNovaFicha.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnNovaFicha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNovaFicha.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNovaFicha.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnNovaFicha.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnNovaFicha.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnNovaFicha.setStartColor(new java.awt.Color(37, 46, 55));
        btnNovaFicha.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnNovaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaFichaActionPerformed(evt);
            }
        });
        sidePanel.add(btnNovaFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 50));

        btnUltimaFicha.setBorder(null);
        btnUltimaFicha.setForeground(new java.awt.Color(255, 255, 255));
        btnUltimaFicha.setText("ULTIMA FICHA");
        btnUltimaFicha.setEndColor(new java.awt.Color(37, 46, 55));
        btnUltimaFicha.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnUltimaFicha.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnUltimaFicha.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnUltimaFicha.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnUltimaFicha.setStartColor(new java.awt.Color(37, 46, 55));
        btnUltimaFicha.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnUltimaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimaFichaActionPerformed(evt);
            }
        });
        sidePanel.add(btnUltimaFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 50));

        btnPorPeriodo.setBorder(null);
        btnPorPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        btnPorPeriodo.setText("GERAR FICHAS POR PERÍODO");
        btnPorPeriodo.setEndColor(new java.awt.Color(37, 46, 55));
        btnPorPeriodo.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnPorPeriodo.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnPorPeriodo.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnPorPeriodo.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnPorPeriodo.setStartColor(new java.awt.Color(37, 46, 55));
        btnPorPeriodo.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnPorPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorPeriodoActionPerformed(evt);
            }
        });
        sidePanel.add(btnPorPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 230, 50));

        txtData1.setBackground(new java.awt.Color(50, 60, 69));
        txtData1.setForeground(new java.awt.Color(240, 240, 240));
        txtData1.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtData1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData1.setLabel("Data Inicial");
        txtData1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtData1FocusGained(evt);
            }
        });
        sidePanel.add(txtData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 155, 51));

        txtData2.setBackground(new java.awt.Color(50, 60, 69));
        txtData2.setForeground(new java.awt.Color(240, 240, 240));
        txtData2.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtData2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData2.setLabel("Data Final");
        txtData2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtData2FocusGained(evt);
            }
        });
        sidePanel.add(txtData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 155, 51));

        jPanel3.setBackground(new java.awt.Color(50, 60, 69));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        sidePanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 230, 250));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 750));

        cardPanel.setLayout(new java.awt.CardLayout());

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelData.setBackground(new java.awt.Color(0, 153, 0));

        btnMessage.setBackground(new java.awt.Color(0, 153, 0));
        btnMessage.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnMessage.setBorderRadius(0);
        btnMessage.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnMessage.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageActionPerformed(evt);
            }
        });

        labelWarningData.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningData.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningData.setText("Cadastro efetuado com sucesso.");

        javax.swing.GroupLayout warningPanelDataLayout = new javax.swing.GroupLayout(warningPanelData);
        warningPanelData.setLayout(warningPanelDataLayout);
        warningPanelDataLayout.setHorizontalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelDataLayout.createSequentialGroup()
                .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelDataLayout.setVerticalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataPanel.add(warningPanelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1080, 40));

        searchPanel.setBackground(new java.awt.Color(50, 60, 69));

        mGradientButton1.setForeground(new java.awt.Color(204, 204, 204));
        mGradientButton1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.SEARCH));
        mGradientButton1.setBorderRadius(58);
        mGradientButton1.setEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(26f));
        mGradientButton1.setHoverEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setHoverStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseExited(evt);
            }
        });
        mGradientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton1ActionPerformed(evt);
            }
        });

        txtPesquisa.setBackground(new java.awt.Color(50, 60, 69));
        txtPesquisa.setForeground(new java.awt.Color(240, 240, 240));
        txtPesquisa.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        txtPesquisa.setLabel("Pesquisar");
        txtPesquisa.setSelectionColor(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap(1004, Short.MAX_VALUE)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchPanelLayout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGap(269, 269, 269)))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(22, 22, 22)))
        );

        dataPanel.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, 100));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(null);
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
        btnExit.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnExit.setBorderRadius(0);
        btnExit.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnExit.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        dataPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 50, 40));

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablePanel.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tablePanel.setHorizontalScrollBar(null);

        tableAlunos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableAlunos.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tableAlunos.setForeground(new java.awt.Color(72, 72, 72));
        tableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Ultima Ficha", "Próxima Ficha", "Ultima Anamnese"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAlunos.setGridColor(new java.awt.Color(255, 255, 255));
        tableAlunos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableAlunos.setRowHeight(30);
        tableAlunos.setSelectionBackground(new java.awt.Color(205, 205, 205));
        tablePanel.setViewportView(tableAlunos);
        if (tableAlunos.getColumnModel().getColumnCount() > 0) {
            tableAlunos.getColumnModel().getColumn(0).setResizable(false);
            tableAlunos.getColumnModel().getColumn(1).setResizable(false);
            tableAlunos.getColumnModel().getColumn(2).setResizable(false);
            tableAlunos.getColumnModel().getColumn(3).setResizable(false);
            tableAlunos.getColumnModel().getColumn(4).setResizable(false);
        }
        tableAlunos.getTableHeader().setFont(new java.awt.Font("Nunito Bold", 0, 14));

        dataPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1050, 550));

        cardPanel.add(dataPanel, "card2");

        formPanelAbrir.setBackground(new java.awt.Color(255, 255, 255));
        formPanelAbrir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelForm.setBackground(new java.awt.Color(255, 51, 51));

        btnError.setBackground(new java.awt.Color(255, 51, 51));
        btnError.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnError.setBorderRadius(0);
        btnError.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnError.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorActionPerformed(evt);
            }
        });

        labelWarningForm.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningForm.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningForm.setText("Preencha os campos obrigatórios.");

        javax.swing.GroupLayout warningPanelFormLayout = new javax.swing.GroupLayout(warningPanelForm);
        warningPanelForm.setLayout(warningPanelFormLayout);
        warningPanelFormLayout.setHorizontalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelFormLayout.createSequentialGroup()
                .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelFormLayout.setVerticalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(warningPanelFormLayout.createSequentialGroup()
                .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        formPanelAbrir.add(warningPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1080, 40));

        botConfirmar.setBackground(new java.awt.Color(51, 51, 51));
        botConfirmar.setBorder(null);
        botConfirmar.setText("Confirmar");
        botConfirmar.setBorderRadius(50);
        botConfirmar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botConfirmar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConfirmarActionPerformed(evt);
            }
        });
        formPanelAbrir.add(botConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 680, 180, 50));

        botCancelar.setBorder(null);
        botCancelar.setText("CANCELAR");
        botCancelar.setBorderRadius(50);
        botCancelar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botCancelar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        formPanelAbrir.add(botCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 680, 180, 50));

        profileImagePanel1.setBackground(new java.awt.Color(255, 255, 255));
        profileImagePanel1.setBorderRadius(120);
        profileImagePanel1.setFillBackground(false);
        profileImagePanel1.setFillImage(true);
        profileImagePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileImagePanel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout profileImagePanel1Layout = new javax.swing.GroupLayout(profileImagePanel1);
        profileImagePanel1.setLayout(profileImagePanel1Layout);
        profileImagePanel1Layout.setHorizontalGroup(
            profileImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        profileImagePanel1Layout.setVerticalGroup(
            profileImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        formPanelAbrir.add(profileImagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, 120));

        labelNome.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        labelNome.setText("jLabel5");
        formPanelAbrir.add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, -1));

        labelIdade.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        labelIdade.setText("jLabel6");
        formPanelAbrir.add(labelIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 50, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel3.setText("Idade");
        formPanelAbrir.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        tabelItens.setBorder(null);
        tabelItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descricao", "Series", "Repetições", "Duração"
            }
        ));
        jScrollPane2.setViewportView(tabelItens);

        formPanelAbrir.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 610, 110));

        mButton4.setBorder(null);
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
        mButton4.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton4.setBorderRadius(0);
        mButton4.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton4.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton4MouseExited(evt);
            }
        });
        mButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1040, Short.MAX_VALUE)
                .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelAbrir.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        try {
            txtProximaAv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtProximaAv.setLabel("Próxima Avaliação");
        formPanelAbrir.add(txtProximaAv, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 150, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPesquisaAtividade.setLabel("Pesquisar Atividade");

        botAddAtiv.setForeground(new java.awt.Color(50, 60, 69));
        botAddAtiv.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.SEARCH));
        botAddAtiv.setBorderRadius(58);
        botAddAtiv.setEndColor(java.awt.Color.lightGray);
        botAddAtiv.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(26f));
        botAddAtiv.setHoverEndColor(java.awt.Color.white);
        botAddAtiv.setHoverStartColor(java.awt.Color.lightGray);
        botAddAtiv.setStartColor(new java.awt.Color(255, 255, 255));
        botAddAtiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botAddAtivMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botAddAtivMouseExited(evt);
            }
        });
        botAddAtiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAddAtivActionPerformed(evt);
            }
        });

        tableAtividades.setBorder(null);
        tableAtividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descricao", "Músculos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAtividades);
        if (tableAtividades.getColumnModel().getColumnCount() > 0) {
            tableAtividades.getColumnModel().getColumn(0).setResizable(false);
            tableAtividades.getColumnModel().getColumn(1).setResizable(false);
            tableAtividades.getColumnModel().getColumn(2).setResizable(false);
        }

        txtDuracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtDuracao.setLabel("Duração (min)");
        txtDuracao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDuracaoFocusLost(evt);
            }
        });

        txtSeries.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtSeries.setLabel("Séries");
        txtSeries.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSeriesFocusLost(evt);
            }
        });

        txtRepeticoes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtRepeticoes.setLabel("Repetições");
        txtRepeticoes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRepeticoesFocusLost(evt);
            }
        });

        botPesqAtividade.setForeground(new java.awt.Color(50, 60, 69));
        botPesqAtividade.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.SEARCH));
        botPesqAtividade.setBorderRadius(58);
        botPesqAtividade.setEndColor(java.awt.Color.lightGray);
        botPesqAtividade.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(26f));
        botPesqAtividade.setHoverEndColor(java.awt.Color.white);
        botPesqAtividade.setHoverStartColor(java.awt.Color.lightGray);
        botPesqAtividade.setStartColor(new java.awt.Color(255, 255, 255));
        botPesqAtividade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botPesqAtividadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botPesqAtividadeMouseExited(evt);
            }
        });
        botPesqAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesqAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPesquisaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botPesqAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botAddAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botPesqAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botAddAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        formPanelAbrir.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 480, 310));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPanturrilhaEsq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPanturrilhaEsq.setLabel("Panturrilha");
        txtPanturrilhaEsq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPanturrilhaEsqFocusLost(evt);
            }
        });
        jPanel4.add(txtPanturrilhaEsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 90, 60));

        txtAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtAltura.setLabel("Altura");
        jPanel4.add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 90, 60));

        txtCintura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCintura.setLabel("Cintura");
        txtCintura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCinturaFocusLost(evt);
            }
        });
        jPanel4.add(txtCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 90, 60));

        txtAbdomen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtAbdomen.setLabel("Abdomen");
        txtAbdomen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAbdomenFocusLost(evt);
            }
        });
        jPanel4.add(txtAbdomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 90, 60));

        txtQuadril.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtQuadril.setLabel("Quadril");
        txtQuadril.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuadrilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuadrilFocusLost(evt);
            }
        });
        jPanel4.add(txtQuadril, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 90, 60));

        txtPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPeso.setLabel("Peso");
        jPanel4.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 60));

        txtBicepsEsq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtBicepsEsq.setLabel("Bíceps");
        txtBicepsEsq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBicepsEsqFocusLost(evt);
            }
        });
        jPanel4.add(txtBicepsEsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 90, 60));

        txtAntebracoEsq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtAntebracoEsq.setLabel("Antebraço");
        txtAntebracoEsq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAntebracoEsqFocusLost(evt);
            }
        });
        jPanel4.add(txtAntebracoEsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, 60));

        txtCoxaEsq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCoxaEsq.setLabel("Coxa");
        txtCoxaEsq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCoxaEsqFocusLost(evt);
            }
        });
        jPanel4.add(txtCoxaEsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 90, 60));

        txtBicepsDir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtBicepsDir.setLabel("Bíceps");
        txtBicepsDir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBicepsDirFocusLost(evt);
            }
        });
        jPanel4.add(txtBicepsDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 90, 60));

        txtAntebracoDir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtAntebracoDir.setLabel("Antebraço");
        txtAntebracoDir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAntebracoDirFocusLost(evt);
            }
        });
        jPanel4.add(txtAntebracoDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 90, 60));

        txtCoxaDir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCoxaDir.setLabel("Coxa");
        txtCoxaDir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCoxaDirFocusLost(evt);
            }
        });
        jPanel4.add(txtCoxaDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 90, 60));

        txtPanturrilhaDir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPanturrilhaDir.setLabel("Panturrilha");
        txtPanturrilhaDir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPanturrilhaDirFocusLost(evt);
            }
        });
        jPanel4.add(txtPanturrilhaDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 90, 60));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel2.setText("Direita");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setText("Esquerda");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        formPanelAbrir.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 530, 500));

        cardPanel.add(formPanelAbrir, "card3");

        bg.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1080, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseEntered
        mButton4.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_mButton4MouseEntered

    private void mButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseExited
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_mButton4MouseExited

    private void mButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton4ActionPerformed
    private void voltar() {

        btnNovaFicha.unselect();
        btnUltimaFicha.unselect();
        btnPorPeriodo.unselect();
        limparCampos();
        makeAllBlack();
        dataPanel.setVisible(true);
        formPanelAbrir.setVisible(false);

    }
    private void btnNovaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaFichaActionPerformed
        int linha = tableAlunos.getSelectedRow();
        int codigo;
        if (linha != -1) {
            int colunas = tableAlunos.getColumnCount();
            for (int x = 0; x < colunas; x++) {
                if (tableAlunos.getColumnName(x).equals("Código")) {
                    codigo = (int) tableAlunos.getValueAt(linha, x);
                    selecionado = contAluno.findByCodigo(codigo);
                    ficha = new Ficha();
                    listaItens = new ArrayList<>();
                    dataPanel.setVisible(false);
                    formPanelAbrir.setVisible(true);
                    setAluno();
                }
            }

        } else {
            labelWarningData.setText("Selecione um aluno.");
            warningPanelData.setBackground(new Color(255, 51, 51));
            btnMessage.setBackground(new Color(255, 51, 51));
            warningPanelData.setVisible(true);
            voltar();

        }


    }//GEN-LAST:event_btnNovaFichaActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed

        warningPanelData.setVisible(false);
        warningPanelForm.setVisible(false);
        voltar();
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConfirmarActionPerformed

        boolean flag = false;
        String message = "";

        if (txtPeso.getText().equals("")) {
            txtPeso.setForeground(errorColor);
            message = "Preencha todos os campos obrigatorios.";
            flag = true;
        }
        if (txtAltura.getText().equals("")) {
            txtAltura.setForeground(errorColor);
            message = "Preencha todos os campos obrigatorios.";
            flag = true;
        }
        if (listaItens.size() == 0) {
            message = "Adicione alguma atividade.";
            flag = true;
        }

        this.repaint();

        if (!flag) {
            
            ficha.setAbdomen(Double.parseDouble(txtAbdomen.getText().replace(',', '.')));
            ficha.setAltura(Double.parseDouble(txtAltura.getText().replace(',', '.')));
            ficha.setAntebracoDir(Double.parseDouble(txtAntebracoDir.getText().replace(',', '.')));
            ficha.setAntebracoEsq(Double.parseDouble(txtAntebracoEsq.getText().replace(',', '.')));
            ficha.setBicepsDir(Double.parseDouble(txtBicepsDir.getText().replace(',', '.')));
            ficha.setBicepsEsq(Double.parseDouble(txtBicepsEsq.getText().replace(',', '.')));
            ficha.setCintura(Double.parseDouble(txtCintura.getText().replace(',', '.')));
            ficha.setCoxaDir(Double.parseDouble(txtCoxaDir.getText().replace(',', '.')));
            ficha.setCoxaEsq(Double.parseDouble(txtCoxaEsq.getText().replace(',', '.')));
            ficha.setDataAv(new Date());
            ficha.setItemdeatividades(listaItens);
            ficha.setMatricula(selecionado);
            ficha.setPanturrilhaDir(Double.parseDouble(txtPanturrilhaDir.getText().replace(',', '.')));
            ficha.setPanturrilhaEsq(Double.parseDouble(txtPanturrilhaEsq.getText().replace(',', '.')));
            ficha.setPeso(Double.parseDouble(txtPeso.getText().replace(',', '.')));
            ficha.setQuadril(Double.parseDouble(txtQuadril.getText().replace(',', '.')));
            ficha.setProxAv(Conversoes.getStringToDate(txtProximaAv.getText()));

            contFicha.persist(ficha);
            message = "Cadastro efetuado com sucesso.";
            warningPanelData.setBackground(new Color(0, 153, 0));
            btnMessage.setBackground(new Color(0, 153, 0));
            labelWarningData.setText(message);
            warningPanelData.setVisible(true);
            voltar();

        } else {

            labelWarningForm.setText(message);
            warningPanelForm.setVisible(true);
            warningPanelForm.setBackground(new Color(255, 51, 51));
            btnError.setBackground(new Color(255, 51, 51));

        }
    }//GEN-LAST:event_botConfirmarActionPerformed

    private void makeAllBlack() {
        txtPeso.setForeground(Color.black);
        txtAltura.setForeground(Color.black);
    }

    private void limparCampos() {
     
        txtPeso.setValue(null);
        txtAbdomen.setValue(null);
        txtAltura.setValue(null);
        txtAntebracoDir.setValue(null);
        txtBicepsDir.setValue(null);
        txtBicepsEsq.setValue(null);
        txtCintura.setValue(null);
        txtCoxaDir.setValue(null);
        txtCoxaEsq.setValue(null);
        txtAntebracoEsq.setValue(null);
        txtDuracao.setValue(null);
        txtPanturrilhaDir.setValue(null);
        txtPanturrilhaEsq.setValue(null);
        txtQuadril.setValue(null);
        txtRepeticoes.setValue(null);
        txtSeries.setValue(null);
    }

    private void btnUltimaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimaFichaActionPerformed

        int linha = tableAlunos.getSelectedRow();
        int codigo;
        if (linha != -1) {

            int colunas = tableAlunos.getColumnCount();
            for (int x = 0; x < colunas; x++) {
                if (tableAlunos.getColumnName(x).equals("Código")) {
                    codigo = (int) tableAlunos.getValueAt(linha, x);
                    selecionado = contAluno.findByCodigo(codigo);

                }
            }

        } else {

            labelWarningData.setText("Selecione um aluno.");
            warningPanelData.setBackground(new Color(255, 51, 51));
            btnMessage.setBackground(new Color(255, 51, 51));
            warningPanelData.setVisible(true);
            voltar();
            //timer
        }


    }//GEN-LAST:event_btnUltimaFichaActionPerformed

    private void mGradientButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton1ActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_mGradientButton1ActionPerformed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseReleased
        try {
            setOpacity((float) 1);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseReleased

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
        try {
            setOpacity((float) 0.9);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseDragged

    private void mGradientButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseEntered
        mGradientButton1.setForeground(Color.white);
    }//GEN-LAST:event_mGradientButton1MouseEntered

    private void mGradientButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseExited
        mGradientButton1.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_mGradientButton1MouseExited

    private void btnErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorActionPerformed
        warningPanelForm.setVisible(false);
    }//GEN-LAST:event_btnErrorActionPerformed

    private void btnMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageActionPerformed
        warningPanelData.setVisible(false);
    }//GEN-LAST:event_btnMessageActionPerformed

    private void txtData1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtData1FocusGained
        txtData1.setForeground(branco);
        if (txtData1.getText().equals("  /  /    "))
            txtData1.setCaretPosition(0);
    }//GEN-LAST:event_txtData1FocusGained

    private void txtData2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtData2FocusGained
        txtData2.setForeground(branco);
        if (txtData2.getText().equals("  /  /    "))
            txtData2.setCaretPosition(0);
    }//GEN-LAST:event_txtData2FocusGained

    private void btnPorPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorPeriodoActionPerformed

        if (!txtData1.getText().equals("  /  /    ") && !txtData2.getText().equals("  /  /    ")) {
            int linha = tableAlunos.getSelectedRow();
            int codigo;
            if (linha != -1) {

                int colunas = tableAlunos.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableAlunos.getColumnName(x).equals("Código")) {
                        codigo = (int) tableAlunos.getValueAt(linha, x);
                        selecionado = contAluno.findByCodigo(codigo);

                    }
                }

            } else {

                labelWarningData.setText("Selecione um aluno.");
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                warningPanelData.setVisible(true);
                voltar();
                //timer
            }

        } else {

            labelWarningData.setText("Digite um período de datas.");
            warningPanelData.setBackground(new Color(255, 51, 51));
            btnMessage.setBackground(new Color(255, 51, 51));
            warningPanelData.setVisible(true);

        }
        voltar();


    }//GEN-LAST:event_btnPorPeriodoActionPerformed

    private void profileImagePanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileImagePanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_profileImagePanel1MouseEntered

    private void botAddAtivMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botAddAtivMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botAddAtivMouseEntered

    private void botAddAtivMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botAddAtivMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botAddAtivMouseExited

    private void botAddAtivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAddAtivActionPerformed
        boolean flag = false;
        Itemdeatividade it = new Itemdeatividade();
        int linha = tableAtividades.getSelectedRow();
        int codigo;
        if (linha != -1) {
            if (!txtDuracao.getText().equals("") && txtSeries.getText().equals("") && txtRepeticoes.getText().equals("")) {
                it.setDuracao(Integer.parseInt(txtDuracao.getText()));
                flag = true;
            } else if (!txtSeries.getText().equals("") && !txtRepeticoes.getText().equals("") && txtDuracao.getText().equals("")) {
                it.setSeries(Integer.parseInt(txtSeries.getText()));
                it.setRepeticoes(Integer.parseInt(txtRepeticoes.getText()));
                flag = true;
            } else {
                labelWarningForm.setText("Digite séries e repetições ou duração");
                warningPanelForm.setBackground(new Color(255, 51, 51));
                btnError.setBackground(new Color(255, 51, 51));
                warningPanelForm.setVisible(true);
                txtSeries.setText("");
                txtRepeticoes.setText("");
                txtDuracao.setText("");
                txtSeries.setValue(null);
                txtRepeticoes.setValue(null);
                txtDuracao.setValue(null);
            }
            if (flag == true) {
                Atividade a;
                int colunas = tableAtividades.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableAtividades.getColumnName(x).equals("Código")) {
                        codigo = (int) tableAtividades.getValueAt(linha, x);
                        a = contAti.findByCodigo(codigo);
                        it.setFicha(ficha);
                        it.setAtividade(a);
                        listaItens.add(it);
                        atualizaTabelaItens();
                    }
                }
            }

        } else {

            labelWarningForm.setText("Selecione uma atividade.");
            warningPanelForm.setBackground(new Color(255, 51, 51));
            btnError.setBackground(new Color(255, 51, 51));
            warningPanelForm.setVisible(true);

            //timer
        }


    }//GEN-LAST:event_botAddAtivActionPerformed

    private void botPesqAtividadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botPesqAtividadeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botPesqAtividadeMouseEntered

    private void botPesqAtividadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botPesqAtividadeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botPesqAtividadeMouseExited
      private void atualizaTabelaItens() {

                DefaultTableModel dtm = (DefaultTableModel) tabelItens.getModel();
                dtm.setNumRows(0);
                for (Itemdeatividade s : listaItens) {
                    dtm.addRow(new Object[]{s.getAtividade().getDescricao(), s.getSeries()==null?"-": s.getSeries(),
                    s.getRepeticoes()==null?"-": s.getRepeticoes(),
                    s.getDuracao()==null?"-": s.getDuracao()});
                }
 
    }
    private void atualizaTabelaAtividade() {
        new Thread() {
            @Override
            public void run() {
                System.out.println("jnf");
                listaAtivides.clear();
                listaAtivides.addAll(contAti.findByDescricao(txtPesquisaAtividade.getText()));
                DefaultTableModel dtm = (DefaultTableModel) tableAtividades.getModel();
                dtm.setNumRows(0);
                for (Atividade s : listaAtivides) {
                    dtm.addRow(new Object[]{s.getCodigo(), s.getDescricao(), s.getMusculo().equals("") ? "-" : s.getMusculo()});
                }
            }
        }.start();
    }
    private void botPesqAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesqAtividadeActionPerformed
        atualizaTabelaAtividade();
    }//GEN-LAST:event_botPesqAtividadeActionPerformed

    private void txtAbdomenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAbdomenFocusLost
        limpa(txtAbdomen);
    }//GEN-LAST:event_txtAbdomenFocusLost

    private void txtSeriesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSeriesFocusLost
       limpa(txtSeries);
    }//GEN-LAST:event_txtSeriesFocusLost

    private void txtRepeticoesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRepeticoesFocusLost
       limpa(txtRepeticoes);
    }//GEN-LAST:event_txtRepeticoesFocusLost

    private void txtDuracaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuracaoFocusLost
        limpa(txtDuracao);
    }//GEN-LAST:event_txtDuracaoFocusLost

    private void txtCinturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCinturaFocusLost
       limpa(txtCintura);
    }//GEN-LAST:event_txtCinturaFocusLost

    private void txtQuadrilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuadrilFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuadrilFocusGained

    private void txtQuadrilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuadrilFocusLost
        limpa(txtQuadril);
    }//GEN-LAST:event_txtQuadrilFocusLost

    private void txtBicepsEsqFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBicepsEsqFocusLost
        limpa(txtBicepsEsq);
    }//GEN-LAST:event_txtBicepsEsqFocusLost

    private void txtAntebracoEsqFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAntebracoEsqFocusLost
       limpa(txtAntebracoEsq);
    }//GEN-LAST:event_txtAntebracoEsqFocusLost

    private void txtCoxaEsqFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCoxaEsqFocusLost
      limpa(txtCoxaEsq);
    }//GEN-LAST:event_txtCoxaEsqFocusLost

    private void txtPanturrilhaEsqFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPanturrilhaEsqFocusLost
      limpa(txtPanturrilhaEsq);
    }//GEN-LAST:event_txtPanturrilhaEsqFocusLost

    private void txtBicepsDirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBicepsDirFocusLost
         limpa(txtBicepsDir);
    }//GEN-LAST:event_txtBicepsDirFocusLost

    private void txtAntebracoDirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAntebracoDirFocusLost
        limpa(txtAntebracoDir);
    }//GEN-LAST:event_txtAntebracoDirFocusLost

    private void txtCoxaDirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCoxaDirFocusLost
        limpa(txtCoxaDir);
    }//GEN-LAST:event_txtCoxaDirFocusLost

    private void txtPanturrilhaDirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPanturrilhaDirFocusLost
         limpa(txtCoxaDir);
    }//GEN-LAST:event_txtPanturrilhaDirFocusLost
    private void limpa(MFormattedTextField f){
        if(f.getText().equals("")){
            f.setValue(null);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormFicha dialog = new FormFicha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton botAddAtiv;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelar;
    private com.hq.swingmaterialdesign.materialdesign.MButton botConfirmar;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton botPesqAtividade;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnError;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnExit;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnMessage;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnNovaFicha;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnPorPeriodo;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnUltimaFicha;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel formPanelAbrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelWarningData;
    private javax.swing.JLabel labelWarningForm;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton4;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton1;
    private com.hq.swingmaterialdesign.materialdesign.MGradientPanel profileImagePanel1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tabelItens;
    private javax.swing.JTable tableAlunos;
    private javax.swing.JTable tableAtividades;
    private javax.swing.JScrollPane tablePanel;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtAbdomen;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtAltura;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtAntebracoDir;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtAntebracoEsq;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtBicepsDir;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtBicepsEsq;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtCintura;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtCoxaDir;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtCoxaEsq;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtData1;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtData2;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtDuracao;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtPanturrilhaDir;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtPanturrilhaEsq;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtPeso;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtPesquisa;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtPesquisaAtividade;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtProximaAv;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtQuadril;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtRepeticoes;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtSeries;
    private javax.swing.JPanel warningPanelData;
    private javax.swing.JPanel warningPanelForm;
    // End of variables declaration//GEN-END:variables
}
