/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleSecretario;
import control.ControleTreinador;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.Secretario;
import model.Treinador;
import org.eclipse.persistence.exceptions.DatabaseException;
import util.Conversoes;
import util.LimitText;

/**
 *
 * @author abner
 */
public class FormTreinador extends javax.swing.JDialog {

    private int xMouse, yMouse;
    private Treinador p = new Treinador();
    private ControleTreinador cp = new ControleTreinador();
    private File file;
    private ArrayList<Treinador> listaPesquisa = new ArrayList();
    private Treinador selecionado;
    private int menuSelection = 0;
    private Color errorColor = new Color(255, 0, 0);

    public FormTreinador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        this.setLocationRelativeTo(null);
        labelImagem.setVisible(false);
        warningPanelForm.setVisible(false);
        warningPanelData.setVisible(false);
    }

    private void atualizaTabela() {
        new Thread() {
            @Override
            public void run() {
                listaPesquisa.clear();
                listaPesquisa.addAll(cp.findByNome(txtPesquisa.getText()));
                DefaultTableModel dtm = (DefaultTableModel) tableTreinadores.getModel();
                dtm.setNumRows(0);
                for (Treinador s : listaPesquisa) {
                    dtm.addRow(new Object[]{s.getCodigo(), s.getNome(), s.getEspecialidade(), Conversoes.getTimeToString(s.getHrEntrada()) + " - " + Conversoes.getTimeToString(s.getHrSaida())});
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        excludeBtn = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        addBtn = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        changeBtn = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnVisualizar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        cardPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        warningPanelData = new javax.swing.JPanel();
        btnMessage = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningData = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        txtPesquisa = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        mGradientButton1 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        btnExit = new com.hq.swingmaterialdesign.materialdesign.MButton();
        tablePanel = new javax.swing.JScrollPane();
        tableTreinadores = new javax.swing.JTable();
        formPanelAdicionar = new javax.swing.JPanel();
        warningPanelForm = new javax.swing.JPanel();
        btnError = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningForm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mButton4 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtNome = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        botCancelar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botConfirmar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        profileImagePanel = new com.hq.swingmaterialdesign.materialdesign.MGradientPanel();
        labelImagem = new javax.swing.JLabel();
        txtNascimento = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtTelefone = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtNumero = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtCidade = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtBairro = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtRua = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtLogin = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtSenha = new com.hq.swingmaterialdesign.materialdesign.MPasswordField();
        txtConfirmar = new com.hq.swingmaterialdesign.materialdesign.MPasswordField();
        txtRg = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtCpf = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtEmail = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtEntrada = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtSaida = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtSalario = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtEspecialidade = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtCref = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        formPanelVisualizar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mButton5 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botCancelar1 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        profileImagePanel1 = new com.hq.swingmaterialdesign.materialdesign.MGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        labelNomeVisu = new javax.swing.JLabel();
        labelNasc = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelCidade = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        labelRua = new javax.swing.JLabel();
        labelRg = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelEspecialidade = new javax.swing.JLabel();
        labelEntrada = new javax.swing.JLabel();
        labelSaida = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        labelSalario = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bgMouseReleased(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(37, 46, 55));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TREINADOR");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 230, 40));

        excludeBtn.setBorder(null);
        excludeBtn.setForeground(new java.awt.Color(255, 255, 255));
        excludeBtn.setText("Excluir");
        excludeBtn.setEndColor(new java.awt.Color(37, 46, 55));
        excludeBtn.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        excludeBtn.setHoverEndColor(new java.awt.Color(37, 46, 55));
        excludeBtn.setHoverStartColor(new java.awt.Color(0, 153, 153));
        excludeBtn.setSelectedColor(new java.awt.Color(0, 153, 153));
        excludeBtn.setStartColor(new java.awt.Color(37, 46, 55));
        excludeBtn.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        excludeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excludeBtnActionPerformed(evt);
            }
        });
        sidePanel.add(excludeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        addBtn.setBorder(null);
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Adicionar");
        addBtn.setEndColor(new java.awt.Color(37, 46, 55));
        addBtn.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        addBtn.setHoverEndColor(new java.awt.Color(37, 46, 55));
        addBtn.setHoverStartColor(new java.awt.Color(0, 153, 153));
        addBtn.setSelectedColor(new java.awt.Color(0, 153, 153));
        addBtn.setStartColor(new java.awt.Color(37, 46, 55));
        addBtn.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        sidePanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        changeBtn.setBorder(null);
        changeBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeBtn.setText("Alterar");
        changeBtn.setEndColor(new java.awt.Color(37, 46, 55));
        changeBtn.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        changeBtn.setHoverEndColor(new java.awt.Color(37, 46, 55));
        changeBtn.setHoverStartColor(new java.awt.Color(0, 153, 153));
        changeBtn.setSelectedColor(new java.awt.Color(0, 153, 153));
        changeBtn.setStartColor(new java.awt.Color(37, 46, 55));
        changeBtn.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });
        sidePanel.add(changeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        btnVisualizar.setBorder(null);
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setText("VISUALIZAR");
        btnVisualizar.setEndColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnVisualizar.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnVisualizar.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnVisualizar.setStartColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        sidePanel.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 50));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 670));

        cardPanel.setLayout(new java.awt.CardLayout());

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelData.setBackground(new java.awt.Color(0, 153, 0));

        btnMessage.setBackground(new java.awt.Color(0, 153, 0));
        btnMessage.setBorder(null);
        btnMessage.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnMessage.setBorderRadius(0);
        btnMessage.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnMessage.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageActionPerformed(evt);
            }
        });

        labelWarningData.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningData.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningData.setText("Cadastro efetuado com sucesso.");

        javax.swing.GroupLayout warningPanelDataLayout = new javax.swing.GroupLayout(warningPanelData);
        warningPanelData.setLayout(warningPanelDataLayout);
        warningPanelDataLayout.setHorizontalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelDataLayout.createSequentialGroup()
                .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelDataLayout.setVerticalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataPanel.add(warningPanelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        searchPanel.setBackground(new java.awt.Color(50, 60, 69));

        txtPesquisa.setBackground(new java.awt.Color(50, 60, 69));
        txtPesquisa.setForeground(new java.awt.Color(240, 240, 240));
        txtPesquisa.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        txtPesquisa.setLabel("Pesquisar");
        txtPesquisa.setSelectionColor(new java.awt.Color(0, 153, 153));

        mGradientButton1.setForeground(new java.awt.Color(204, 204, 204));
        mGradientButton1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.SEARCH));
        mGradientButton1.setBorderRadius(58);
        mGradientButton1.setEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(26f));
        mGradientButton1.setHoverEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setHoverStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseExited(evt);
            }
        });
        mGradientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        dataPanel.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 100));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(null);
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
        btnExit.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnExit.setBorderRadius(0);
        btnExit.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnExit.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        dataPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 50, 40));

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablePanel.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tablePanel.setHorizontalScrollBar(null);

        tableTreinadores.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableTreinadores.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tableTreinadores.setForeground(new java.awt.Color(72, 72, 72));
        tableTreinadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Especialidade", "Horário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTreinadores.setGridColor(new java.awt.Color(255, 255, 255));
        tableTreinadores.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableTreinadores.setRowHeight(30);
        tableTreinadores.setSelectionBackground(new java.awt.Color(205, 205, 205));
        tablePanel.setViewportView(tableTreinadores);
        tableTreinadores.getTableHeader().setFont(new java.awt.Font("Nunito Bold", 0, 14));

        dataPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 670, 390));

        cardPanel.add(dataPanel, "card2");

        formPanelAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        formPanelAdicionar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelForm.setBackground(new java.awt.Color(255, 51, 51));

        btnError.setBackground(new java.awt.Color(255, 51, 51));
        btnError.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnError.setBorderRadius(0);
        btnError.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnError.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorActionPerformed(evt);
            }
        });

        labelWarningForm.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningForm.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningForm.setText("Preencha os campos corretamente.");

        javax.swing.GroupLayout warningPanelFormLayout = new javax.swing.GroupLayout(warningPanelForm);
        warningPanelForm.setLayout(warningPanelFormLayout);
        warningPanelFormLayout.setHorizontalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelFormLayout.createSequentialGroup()
                .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelFormLayout.setVerticalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelAdicionar.add(warningPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        mButton4.setBorder(null);
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
        mButton4.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton4.setBorderRadius(0);
        mButton4.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton4.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton4MouseExited(evt);
            }
        });
        mButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelAdicionar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        txtNome.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtNome.setLabel("Nome");
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });
        txtNome.setDocument(new LimitText(50));
        formPanelAdicionar.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 58, 503, 51));

        botCancelar.setBorder(null);
        botCancelar.setText("CANCELAR");
        botCancelar.setBorderRadius(50);
        botCancelar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botCancelar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        formPanelAdicionar.add(botCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 514, 180, 50));

        botConfirmar.setBackground(new java.awt.Color(51, 51, 51));
        botConfirmar.setBorder(null);
        botConfirmar.setText("Confirmar");
        botConfirmar.setBorderRadius(50);
        botConfirmar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botConfirmar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConfirmarActionPerformed(evt);
            }
        });
        formPanelAdicionar.add(botConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 514, 180, 50));

        profileImagePanel.setBackground(new java.awt.Color(255, 255, 255));
        profileImagePanel.setBorderRadius(120);
        profileImagePanel.setFillBackground(false);
        profileImagePanel.setFillImage(true);
        profileImagePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileImagePanelMouseEntered(evt);
            }
        });

        labelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/profileImageHover.png"))); // NOI18N
        labelImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImagemMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelImagemMouseExited(evt);
            }
        });

        javax.swing.GroupLayout profileImagePanelLayout = new javax.swing.GroupLayout(profileImagePanel);
        profileImagePanel.setLayout(profileImagePanelLayout);
        profileImagePanelLayout.setHorizontalGroup(
            profileImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profileImagePanelLayout.setVerticalGroup(
            profileImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        formPanelAdicionar.add(profileImagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 58, 120, 120));

        txtNascimento.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimento.setLabel("Data de Nascimento");
        txtNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNascimentoFocusGained(evt);
            }
        });
        formPanelAdicionar.add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 116, 155, 51));

        txtTelefone.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setLabel("Telefone");
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusGained(evt);
            }
        });
        formPanelAdicionar.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 174, 168, 54));

        txtNumero.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtNumero.setLabel("Número");
        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroFocusGained(evt);
            }
        });
        txtNumero.setDocument(new LimitText(5));
        formPanelAdicionar.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 290, 117, 50));

        txtCidade.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtCidade.setLabel("Cidade");
        txtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCidadeFocusGained(evt);
            }
        });
        txtCidade.setDocument(new LimitText(50));
        formPanelAdicionar.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 234, 302, 50));

        txtBairro.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtBairro.setLabel("Bairro");
        txtBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBairroFocusGained(evt);
            }
        });
        txtBairro.setDocument(new LimitText(50));
        formPanelAdicionar.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 234, 195, 50));

        txtRua.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtRua.setLabel("Logradouro");
        txtRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuaFocusGained(evt);
            }
        });
        txtRua.setDocument(new LimitText(50));
        formPanelAdicionar.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 290, 380, 50));

        txtLogin.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtLogin.setLabel("Nome de usuário");
        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginFocusGained(evt);
            }
        });
        txtLogin.setDocument(new LimitText(10));
        formPanelAdicionar.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 347, 191, 50));

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSenha.setLabel("Senha");
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
        });
        txtSenha.setDocument(new LimitText(10));
        formPanelAdicionar.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 346, 155, 50));

        txtConfirmar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtConfirmar.setLabel("Confirmar Senha");
        txtConfirmar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmarFocusGained(evt);
            }
        });
        txtConfirmar.setDocument(new LimitText(10));
        formPanelAdicionar.add(txtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 346, 145, 50));

        txtRg.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setLabel("RG");
        txtRg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRgFocusGained(evt);
            }
        });
        formPanelAdicionar.add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 115, 168, 53));

        txtCpf.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setLabel("CPF");
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
        });
        formPanelAdicionar.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 115, 168, 53));

        txtEmail.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtEmail.setLabel("E-mail");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });
        txtEmail.setDocument(new LimitText(50));
        formPanelAdicionar.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 174, 329, 54));

        txtEntrada.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txtEntrada.setLabel("Horário de entrada");
        txtEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEntradaFocusGained(evt);
            }
        });
        formPanelAdicionar.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 160, 50));

        txtSaida.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txtSaida.setLabel("Horário de saída");
        txtSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSaidaFocusGained(evt);
            }
        });
        formPanelAdicionar.add(txtSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 150, 50));

        txtSalario.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtSalario.setLabel("Salário");
        txtSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSalarioFocusGained(evt);
            }
        });
        formPanelAdicionar.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 180, 50));

        txtEspecialidade.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtEspecialidade.setLabel("Especialidade");
        txtCref.setDocument(new LimitText(11));
        txtEspecialidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEspecialidadeFocusGained(evt);
            }
        });
        formPanelAdicionar.add(txtEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 260, 50));

        txtCref.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtCref.setLabel("CREF");
        txtCref.setDocument(new LimitText(11));
        txtCref.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCrefFocusGained(evt);
            }
        });
        formPanelAdicionar.add(txtCref, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 240, 50));

        cardPanel.add(formPanelAdicionar, "card3");

        formPanelVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        formPanelVisualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mButton5.setBorder(null);
        mButton5.setForeground(new java.awt.Color(153, 153, 153));
        mButton5.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton5.setBorderRadius(0);
        mButton5.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton5.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton5MouseExited(evt);
            }
        });
        mButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelVisualizar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        botCancelar1.setBorder(null);
        botCancelar1.setText("Voltar");
        botCancelar1.setBorderRadius(50);
        botCancelar1.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botCancelar1.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelar1ActionPerformed(evt);
            }
        });
        formPanelVisualizar.add(botCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 180, 50));

        profileImagePanel1.setBackground(new java.awt.Color(255, 255, 255));
        profileImagePanel1.setBorderRadius(120);
        profileImagePanel1.setFillBackground(false);
        profileImagePanel1.setFillImage(true);
        profileImagePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileImagePanel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout profileImagePanel1Layout = new javax.swing.GroupLayout(profileImagePanel1);
        profileImagePanel1.setLayout(profileImagePanel1Layout);
        profileImagePanel1Layout.setHorizontalGroup(
            profileImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        profileImagePanel1Layout.setVerticalGroup(
            profileImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        formPanelVisualizar.add(profileImagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 120, 120));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel2.setText("Nome");
        formPanelVisualizar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel3.setText("Telefone");
        formPanelVisualizar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel4.setText("E-mail");
        formPanelVisualizar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel5.setText("Data Nascimento");
        formPanelVisualizar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel6.setText("Rua");
        formPanelVisualizar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 40, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel7.setText("Bairro");
        formPanelVisualizar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 50, -1));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel8.setText("Cidade");
        formPanelVisualizar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, -1));

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel9.setText("CPF");
        formPanelVisualizar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel10.setText("RG");
        formPanelVisualizar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel12.setText("Login");
        formPanelVisualizar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));
        formPanelVisualizar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 200, 10));
        formPanelVisualizar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 650, 10));
        formPanelVisualizar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 650, 10));
        formPanelVisualizar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 650, 10));
        formPanelVisualizar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 650, 10));

        labelNomeVisu.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelNomeVisu.setText("jLabel13");
        formPanelVisualizar.add(labelNomeVisu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 590, -1));

        labelNasc.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelNasc.setText("jLabel11");
        formPanelVisualizar.add(labelNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 320, -1));

        labelEmail.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelEmail.setText("jLabel14");
        formPanelVisualizar.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 280, -1));

        labelTelefone.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelTelefone.setText("jLabel15");
        formPanelVisualizar.add(labelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 210, -1));

        labelCidade.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelCidade.setText("jLabel11");
        formPanelVisualizar.add(labelCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 580, -1));

        labelBairro.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelBairro.setText("jLabel11");
        formPanelVisualizar.add(labelBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 220, -1));

        labelRua.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelRua.setText("jLabel11");
        formPanelVisualizar.add(labelRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 310, -1));

        labelRg.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelRg.setText("jLabel11");
        formPanelVisualizar.add(labelRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 210, -1));

        labelCpf.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelCpf.setText("jLabel11");
        formPanelVisualizar.add(labelCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 210, -1));

        labelLogin.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelLogin.setText("jLabel11");
        formPanelVisualizar.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 150, -1));
        formPanelVisualizar.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 650, 10));

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel11.setText("Especialidade");
        formPanelVisualizar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel13.setText("Horário entrada");
        formPanelVisualizar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel14.setText("Saída");
        formPanelVisualizar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        labelEspecialidade.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelEspecialidade.setText("jLabel15");
        formPanelVisualizar.add(labelEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 530, -1));

        labelEntrada.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelEntrada.setText("jLabel15");
        formPanelVisualizar.add(labelEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 110, -1));

        labelSaida.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelSaida.setText("jLabel15");
        formPanelVisualizar.add(labelSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 130, -1));
        formPanelVisualizar.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 650, 10));

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel15.setText("Salário");
        formPanelVisualizar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, -1, -1));

        labelSalario.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        labelSalario.setText("jLabel16");
        formPanelVisualizar.add(labelSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 160, -1));
        formPanelVisualizar.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 650, 10));
        formPanelVisualizar.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 233, 650, 10));

        cardPanel.add(formPanelVisualizar, "card3");

        bg.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 710, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excludeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excludeBtnActionPerformed
        int linha = tableTreinadores.getSelectedRow();
        int codigo;
        Treinador sExcluir = null;
        if (menuSelection == 0) {
            if (linha != -1) {
                menuSelection = 3;
                int colunas = tableTreinadores.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableTreinadores.getColumnName(x).equals("Código")) {
                        codigo = (int) tableTreinadores.getValueAt(linha, x);
                        sExcluir = cp.findByCodigo(codigo);

                    }
                }
                if (sExcluir != null) {
                    int op = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir " + sExcluir.getNome() + "?");
                    if (op == 0) {
                        try {
                            cp.delete(sExcluir);
                            DefaultTableModel dtm = (DefaultTableModel) tableTreinadores.getModel();
                            dtm.removeRow(linha);
                            warningPanelData.setVisible(true);
                            warningPanelData.setBackground(new Color(0, 153, 0));
                            btnMessage.setBackground(new Color(0, 153, 0));
                            labelWarningData.setText("Excluído com sucesso!");
                            menuSelection = 0;

                        } catch (Exception e) {
                            warningPanelData.setVisible(true);
                            warningPanelData.setBackground(new Color(255, 51, 51));
                            btnMessage.setBackground(new Color(255, 51, 51));
                            labelWarningData.setText("Este treinador possui registros vinculados.\nNão foi possível realizar a exclusão!");
                            menuSelection = 0;
                            excludeBtn.unselect();
                        }
                    }

                }
                voltar();

            } else {
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                labelWarningData.setText("Selecione um aluno.");
            }
        } else {
           if (menuSelection == 1) {
                addBtn.select();
                excludeBtn.unselect();
            } else if (menuSelection==2){
                changeBtn.select();
                excludeBtn.unselect();
            }else if(menuSelection==4){
                btnVisualizar.select();
                excludeBtn.unselect();
            }
        }
    }//GEN-LAST:event_excludeBtnActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseEntered
        mButton4.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_mButton4MouseEntered

    private void mButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseExited
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_mButton4MouseExited

    private void mButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton4ActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (menuSelection == 0) {
            p = new Treinador();
            menuSelection = 1;
            selecionado =null;
            dataPanel.setVisible(false);
            formPanelAdicionar.setVisible(true);
            selecionado = null;
            txtCpf.setEditable(true);
            limparCampos();
        } else {
            if (menuSelection == 4) {
                btnVisualizar.select();
                addBtn.unselect();
            } else if (menuSelection==2){
                changeBtn.select();
                addBtn.unselect();
            }else if(menuSelection==3){
                excludeBtn.select();
                addBtn.unselect();
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed

        warningPanelData.setVisible(false);
        warningPanelForm.setVisible(false);
        voltar();

    }//GEN-LAST:event_botCancelarActionPerformed
    private void voltar() {
        menuSelection = 0;
        addBtn.unselect();
        btnVisualizar.unselect();
        changeBtn.unselect();
        excludeBtn.unselect();
        limparCampos();
        makeAllBlack();
        dataPanel.setVisible(true);
        formPanelAdicionar.setVisible(false);
        formPanelVisualizar.setVisible(false);
        
    }
    private void botConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConfirmarActionPerformed
        byte[] imageInByte = null;

        if (file != null) {
            imageInByte = new byte[(int) file.length()];
            FileInputStream fis = null;
            try {
                fis = new FileInputStream(file);
                fis.read(imageInByte);
                fis.close();
            } catch (IOException ex) {
                Logger.getLogger(FormTreinador.class.getName()).log(Level.SEVERE, null, ex);
                fis = null;
            }
        }
        boolean flag = false;
        String message = "";
        boolean passerr = false;
        if (txtCref.getText().equals("")) {
            txtCref.setForeground(new Color(255, 102, 102));
            flag = true;
        }

        if (txtEspecialidade.getText().equals("")) {
            txtEspecialidade.setForeground(new Color(255, 102, 102));
            flag = true;
        }

        if (txtNome.getText().equals("")) {
            txtNome.setForeground(errorColor);
            flag = true;
        }
        if (txtTelefone.getText().equals("(  )      -    ")) {
            txtTelefone.setForeground(errorColor);
            flag = true;
        }
        if (txtNascimento.getText().equals("  /  /    ")) {
            txtNascimento.setForeground(errorColor);
            flag = true;
        }
        if (txtCpf.getText().equals("   .   .   -  ")) {
            txtCpf.setForeground(errorColor);
            flag = true;
        }
        if (txtRg.getText().equals("  .   .   - ")) {
            txtRg.setForeground(errorColor);
            flag = true;
        }
        if (txtEmail.getText().equals("")) {
            txtEmail.setForeground(errorColor);
            flag = true;
        }
        if (txtCidade.getText().equals("")) {
            txtCidade.setForeground(errorColor);
            flag = true;
        }
        if (txtBairro.getText().equals("")) {
            txtBairro.setForeground(errorColor);
            flag = true;
        }
        if (txtRua.getText().equals("")) {
            txtRua.setForeground(errorColor);
            flag = true;
        }
        if (txtNumero.getText().equals("")) {
            txtNumero.setForeground(errorColor);
            flag = true;
        }
        if (txtLogin.getText().equals("")) {
            txtLogin.setForeground(errorColor);
            flag = true;
        }
        if (txtSenha.getText().equals("")) {
            txtSenha.setForeground(errorColor);
            flag = true;
        }
        if (txtSenha.getPassword().length < 4) {
            txtSenha.setForeground(errorColor);
            passerr = true;
        }
        if (txtConfirmar.getText().equals("")) {
            txtConfirmar.setForeground(errorColor);
            flag = true;
        }
        if (txtEntrada.getText().equals("")) {
            txtEntrada.setForeground(errorColor);
            flag = true;
        }
        if (txtSaida.getText().equals("")) {
            txtSaida.setForeground(errorColor);
            flag = true;
        }
        if (txtSalario.getText().equals("")) {
            txtSalario.setForeground(errorColor);
            flag = true;
        }
        if (!txtSalario.getText().equals("") && Double.parseDouble(txtSalario.getText().replace(',', '.')) <= 0) {
            txtSalario.setForeground(errorColor);
            flag = true;
        }

        this.repaint();

        if (flag) {
            message = "Preencha todos os campos corretamente.";

        }
        if (passerr) {
            message += " A senha deve ter no mínimo 4 caracteres!";

        }
        if (!txtSenha.getText().equals(txtConfirmar.getText()) && !passerr) {
            txtSenha.setForeground(errorColor);
            message += " As senhas não correspondem";
            flag = true;
        }
        if (Conversoes.getStringToTime(txtEntrada.getText()).after(Conversoes.getStringToTime(txtSaida.getText()))) {
            txtSaida.setForeground(errorColor);
            flag = true;
            message += " O horário de entrada deve anteceder o de saída";
        }

        if (!flag && !passerr) {
            p.setNome(txtNome.getText());
            p.setCidade(txtCidade.getText());
            p.setBairro(txtBairro.getText());
            p.setCpf(txtCpf.getText());
            p.setDataNasc(Conversoes.getStringToDate(txtNascimento.getText()));
            p.setEmail(txtEmail.getText());
            p.setLogin(txtLogin.getText());
            p.setNumero(Integer.parseInt(txtNumero.getText()));
            p.setRg(txtRg.getText());
            p.setSenha(txtSenha.getText());
            p.setTelefone(txtTelefone.getText());
            p.setEspecialidade(txtEspecialidade.getText());
            p.setHrEntrada(Conversoes.getStringToTime(txtEntrada.getText()));
            p.setHrSaida(Conversoes.getStringToTime(txtSaida.getText()));

            p.setSalario(Double.parseDouble(txtSalario.getText().replace(',', '.')));
            p.setCREF(txtCref.getText());

            p.setRua(txtRua.getText());

            if (file != null) {
                p.setImagem(imageInByte);
            }
            if (selecionado == null) {
                try {

                    cp.persist(p);
                    message = "Cadastro efetuado com sucesso.";
                    warningPanelData.setBackground(new Color(0, 153, 0));
                    btnMessage.setBackground(new Color(0, 153, 0));
                    labelWarningData.setText(message);
                    warningPanelData.setVisible(true);
                    voltar();
                } catch (Exception ex) {
                    message = "Login ou cpf ja cadastrado.";
                    txtLogin.requestFocus();
                    txtLogin.setForeground(errorColor);
                    warningPanelForm.setBackground(new Color(255, 51, 51));
                    btnError.setBackground(new Color(255, 51, 51));
                    labelWarningForm.setText(message);
                    warningPanelForm.setVisible(true);
                }
            } else {
                p.setCodigo(selecionado.getCodigo());
                cp.alter(p);
                message = "Alteração efetuada com sucesso.";
                labelWarningData.setText(message);
                warningPanelData.setBackground(new Color(0, 153, 0));
                btnMessage.setBackground(new Color(0, 153, 0));
                warningPanelData.setVisible(true);
                voltar();
            }

        } else {
            labelWarningForm.setText(message);
            warningPanelForm.setVisible(true);
            warningPanelForm.setBackground(new Color(255, 51, 51));
            btnError.setBackground(new Color(255, 51, 51));
        }
    }//GEN-LAST:event_botConfirmarActionPerformed

    private void makeAllBlack() {
        txtNome.setForeground(Color.black);
        txtTelefone.setForeground(Color.black);
        txtNascimento.setForeground(Color.black);
        txtCpf.setForeground(Color.black);
        txtRg.setForeground(Color.black);
        txtEmail.setForeground(Color.black);
        txtCidade.setForeground(Color.black);
        txtBairro.setForeground(Color.black);
        txtRua.setForeground(Color.black);
        txtNumero.setForeground(Color.black);
        txtLogin.setForeground(Color.black);
        txtSenha.setForeground(Color.black);
        txtConfirmar.setForeground(Color.black);
        txtEntrada.setForeground(Color.black);
        txtSaida.setForeground(Color.black);
        txtSalario.setForeground(Color.black);
        txtEspecialidade.setForeground(new Color(109, 109, 109));
        txtCref.setForeground(new Color(109, 109, 109));
    }

    private void limparCampos() {
        txtNome.setText("");
        txtTelefone.setValue("");
        txtNascimento.setValue("");
        txtCpf.setValue("");
        txtRg.setText("");
        txtEmail.setText("");
        txtCidade.setText("");
        txtBairro.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtLogin.setText("");
        txtSenha.setText("");
        txtConfirmar.setText("");
        txtEntrada.setText("");
        txtSaida.setText("");
        txtSalario.setText("");
        txtEspecialidade.setText("");
        txtCref.setText("");

        String imagePath = "/com/hq/swingmaterialdesign/images/profile.jpg";
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        Image img = icon.getImage();
        profileImagePanel.setImage(img);

    }
    private void profileImagePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileImagePanelMouseEntered
        labelImagem.setVisible(true);
    }//GEN-LAST:event_profileImagePanelMouseEntered

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        if (menuSelection == 0) {
            int linha = tableTreinadores.getSelectedRow();
            int codigo;
            if (linha != -1) {
                menuSelection = 2;
                int colunas = tableTreinadores.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableTreinadores.getColumnName(x).equals("Código")) {
                        codigo = (int) tableTreinadores.getValueAt(linha, x);
                        selecionado = cp.findByCodigo(codigo);
                        setTreinador();
                        dataPanel.setVisible(false);
                        formPanelAdicionar.setVisible(true);
                    }
                }

            } else {
                changeBtn.unselect();
                labelWarningData.setText("Selecione um treinador.");
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                menuSelection = 0;
                //timer
            }
        } else {
            if (menuSelection == 1) {
                addBtn.select();
                changeBtn.unselect();
            } else if (menuSelection==3){
                excludeBtn.select();
                changeBtn.unselect();
            }else if(menuSelection==4){
                btnVisualizar.select();
                changeBtn.unselect();
            }
        }

    }//GEN-LAST:event_changeBtnActionPerformed

    private void mGradientButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton1ActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_mGradientButton1ActionPerformed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseReleased

        try {
            setOpacity((float) 1);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseReleased

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged

        setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
        try {
            setOpacity((float) 0.9);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseDragged

    private void mGradientButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseEntered
        mGradientButton1.setForeground(Color.white);
    }//GEN-LAST:event_mGradientButton1MouseEntered

    private void mGradientButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseExited
        mGradientButton1.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_mGradientButton1MouseExited

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setForeground(Color.black);
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained
        txtCpf.setForeground(Color.black);
        if (txtCpf.getText().equals("   .   .   -  "))
            txtCpf.setCaretPosition(0);
    }//GEN-LAST:event_txtCpfFocusGained

    private void txtRgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRgFocusGained
        txtRg.setForeground(Color.black);
        if (txtRg.getText().equals("  .   .   - "))
            txtRg.setCaretPosition(0);
    }//GEN-LAST:event_txtRgFocusGained

    private void txtNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNascimentoFocusGained
        txtNascimento.setForeground(Color.black);
        if (txtNascimento.getText().equals("  /  /    "))
            txtNascimento.setCaretPosition(0);
    }//GEN-LAST:event_txtNascimentoFocusGained

    private void txtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusGained
        txtTelefone.setForeground(Color.black);
    }//GEN-LAST:event_txtTelefoneFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        txtEmail.setForeground(Color.black);
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusGained
        txtCidade.setForeground(Color.black);
    }//GEN-LAST:event_txtCidadeFocusGained

    private void txtBairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBairroFocusGained
        txtBairro.setForeground(Color.black);
    }//GEN-LAST:event_txtBairroFocusGained

    private void txtRuaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuaFocusGained
        txtRua.setForeground(Color.black);
    }//GEN-LAST:event_txtRuaFocusGained

    private void txtNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusGained
        txtNumero.setForeground(Color.black);
    }//GEN-LAST:event_txtNumeroFocusGained

    private void txtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusGained
        txtLogin.setForeground(Color.black);
    }//GEN-LAST:event_txtLoginFocusGained

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        txtSenha.setForeground(Color.black);
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtConfirmarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmarFocusGained
        txtConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_txtConfirmarFocusGained

    private void txtEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEntradaFocusGained
        txtEntrada.setForeground(Color.black);
        if (txtEntrada.getText().equals(""))
            txtEntrada.setCaretPosition(0);
    }//GEN-LAST:event_txtEntradaFocusGained

    private void txtSaidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaidaFocusGained
        txtSaida.setForeground(Color.black);
        if (txtSaida.getText().equals(""))
            txtSaida.setCaretPosition(0);
    }//GEN-LAST:event_txtSaidaFocusGained

    private void txtSalarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalarioFocusGained
        txtSalario.setForeground(Color.black);
        if (txtSalario.getText().equals(""))
            txtSalario.setCaretPosition(0);
    }//GEN-LAST:event_txtSalarioFocusGained

    private void labelImagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImagemMouseExited
        labelImagem.setVisible(false);
    }//GEN-LAST:event_labelImagemMouseExited

    private void labelImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImagemMouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Selecione a imagem de perfil");
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter ext = new FileNameExtensionFilter("Imagem", "png", "jpg", "bmp");

        jfc.setFileFilter(ext);

        int r = jfc.showOpenDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            Image image = null;
            try {
                image = ImageIO.read(file);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Impossível carregar imagem!");
            } finally {
                System.out.println(file.getAbsolutePath());
                profileImagePanel.setImage(image);
                profileImagePanel.repaint();
            }
        }
    }//GEN-LAST:event_labelImagemMouseClicked

    private void btnErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorActionPerformed
        warningPanelForm.setVisible(false);
    }//GEN-LAST:event_btnErrorActionPerformed

    private void btnMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageActionPerformed
        warningPanelData.setVisible(false);
    }//GEN-LAST:event_btnMessageActionPerformed

    private void txtEspecialidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEspecialidadeFocusGained
        txtEspecialidade.setForeground(Color.black);
    }//GEN-LAST:event_txtEspecialidadeFocusGained

    private void txtCrefFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCrefFocusGained
        txtCref.setForeground(Color.black);
    }//GEN-LAST:event_txtCrefFocusGained

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
       if (menuSelection == 0) {
            int linha = tableTreinadores.getSelectedRow();
            int codigo;
            if (linha != -1) {
                menuSelection = 4;
                int colunas = tableTreinadores.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableTreinadores.getColumnName(x).equals("Código")) {
                        codigo = (int) tableTreinadores.getValueAt(linha, x);
                        selecionado = cp.findByCodigo(codigo);
                        setTreinadorVisualizar();
                        dataPanel.setVisible(false);
                        formPanelVisualizar.setVisible(true);
                    }
                }

            } else {
                changeBtn.unselect();
                labelWarningData.setText("Selecione um treinador.");
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                menuSelection = 0;
                //timer
            }
        } else {
           if (menuSelection == 1) {
                addBtn.select();
                btnVisualizar.unselect();
            } else if (menuSelection==2){
                changeBtn.select();
                btnVisualizar.unselect();
            }else if(menuSelection==3){
                excludeBtn.select();
                btnVisualizar.unselect();
            }
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void mButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mButton5MouseEntered

    private void mButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_mButton5MouseExited

    private void mButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton5ActionPerformed
      dispose();
    }//GEN-LAST:event_mButton5ActionPerformed

    private void botCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelar1ActionPerformed
        voltar();
    }//GEN-LAST:event_botCancelar1ActionPerformed

    private void profileImagePanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileImagePanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_profileImagePanel1MouseEntered

    private void setTreinador() {
        if (selecionado.getImagem() != null) {
            ImageIcon im = new ImageIcon(selecionado.getImagem());
            profileImagePanel.setImage(im.getImage());
            profileImagePanel.repaint();
        }
        txtNome.setText(selecionado.getNome());
        txtTelefone.setText(selecionado.getTelefone());
        txtNascimento.setText(Conversoes.getDateToString(selecionado.getDataNasc()));
        txtCpf.setText(selecionado.getCpf());
        txtCpf.setEditable(false);
        txtCpf.setBackground(Color.WHITE);
        txtRg.setText(selecionado.getRg());
        txtEmail.setText(selecionado.getEmail());
        txtCidade.setText(selecionado.getCidade());
        txtBairro.setText(selecionado.getBairro());
        txtRua.setText(selecionado.getRua());
        txtNumero.setText(Integer.toString(selecionado.getNumero()));
        txtLogin.setText(selecionado.getLogin());
        txtEntrada.setText(Conversoes.getTimeToString(selecionado.getHrEntrada()));
        txtSaida.setText(Conversoes.getTimeToString(selecionado.getHrSaida()));
        txtSalario.setText(Double.toString(selecionado.getSalario()));
        txtEspecialidade.setText(selecionado.getEspecialidade());
        txtCref.setText(selecionado.getCREF());
    }
    private void setTreinadorVisualizar(){
        if (selecionado.getImagem() != null) {
            ImageIcon im = new ImageIcon(selecionado.getImagem());
            profileImagePanel1.setImage(im.getImage());
            profileImagePanel1.repaint();
        }
        labelBairro.setText(selecionado.getBairro());
        labelCidade.setText(selecionado.getCidade() );
        labelRua.setText(selecionado.getRua() + " "+ selecionado.getNumero());
        labelNomeVisu.setText(selecionado.getNome());
        labelNasc.setText(Conversoes.getDateToString(selecionado.getDataNasc()));
        labelLogin.setText(selecionado.getLogin());
        labelCpf.setText(selecionado.getCpf());
        labelRg.setText(selecionado.getRg());
        labelEmail.setText(selecionado.getEmail());
        labelTelefone.setText(selecionado.getTelefone());
        labelEntrada.setText(Conversoes.getTimeToString(selecionado.getHrEntrada()));
        labelSaida.setText(Conversoes.getTimeToString(selecionado.getHrSaida()));
        labelEspecialidade.setText(selecionado.getEspecialidade());
        labelSalario.setText("R$ "+Double.toString(selecionado.getSalario()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormTreinador dialog = new FormTreinador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton addBtn;
    private javax.swing.JPanel bg;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelar;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelar1;
    private com.hq.swingmaterialdesign.materialdesign.MButton botConfirmar;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnError;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnExit;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnMessage;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnVisualizar;
    private javax.swing.JPanel cardPanel;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton changeBtn;
    private javax.swing.JPanel dataPanel;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton excludeBtn;
    private javax.swing.JPanel formPanelAdicionar;
    private javax.swing.JPanel formPanelVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEntrada;
    private javax.swing.JLabel labelEspecialidade;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNasc;
    private javax.swing.JLabel labelNomeVisu;
    private javax.swing.JLabel labelRg;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelSaida;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelWarningData;
    private javax.swing.JLabel labelWarningForm;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton4;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton5;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton1;
    private com.hq.swingmaterialdesign.materialdesign.MGradientPanel profileImagePanel;
    private com.hq.swingmaterialdesign.materialdesign.MGradientPanel profileImagePanel1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JTable tableTreinadores;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtBairro;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtCidade;
    private com.hq.swingmaterialdesign.materialdesign.MPasswordField txtConfirmar;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtCpf;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtCref;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtEmail;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtEntrada;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtEspecialidade;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtLogin;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtNascimento;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtNome;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtNumero;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtPesquisa;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtRg;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtRua;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtSaida;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtSalario;
    private com.hq.swingmaterialdesign.materialdesign.MPasswordField txtSenha;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtTelefone;
    private javax.swing.JPanel warningPanelData;
    private javax.swing.JPanel warningPanelForm;
    // End of variables declaration//GEN-END:variables
}
