/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleCaixa;
import control.ControleSecretario;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Caixa;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import util.Conversoes;

/**
 *
 * @author abner
 */
public class FormCaixa extends javax.swing.JDialog {

    private int xMouse, yMouse;
    private Caixa p = new Caixa();
    private ControleCaixa contCaixa = new ControleCaixa();
    private File file;
    private ArrayList<Caixa> listaPesquisa = new ArrayList();
    private Caixa selecionado;
    private int menuSelection = 0;
    private Color errorColor = new Color(255, 0, 0);
    private Color branco = new Color(240, 240, 240);

    public FormCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        this.setLocationRelativeTo(null);

        warningPanelForm.setVisible(false);
        warningPanelData.setVisible(false);
        warningPanelForm1.setVisible(false);
    }

    private void atualizaTabela() {
        new Thread() {
            @Override
            public void run() {
                listaPesquisa.clear();
                if (!txtData1.getText().equals("  /  /    ") || !txtData1.getText().equals("  /  /    ")) {
                    listaPesquisa.addAll(contCaixa.findByDatas(txtData1.getText(), txtData2.getText()));
                    DefaultTableModel dtm = (DefaultTableModel) tableAlunos.getModel();
                    dtm.setNumRows(0);
                    for (Caixa s : listaPesquisa) {
                        dtm.addRow(new Object[]{s.getCodigo(),
                            s.getSecretario().getNome(),
                            Conversoes.getDateFormatedToString(s.getData()), Conversoes.getStringOfTime(s.getHrAbertura()) + " - " + (s.getHrFechamento() == null ? " " : Conversoes.getStringOfTime(s.getHrFechamento())),
                            s.getHrFechamento() == null ? "Aberto" : "Fechado"});
                    }
                } else {
                    warningPanelData.setBackground(new Color(255, 51, 51));
                    btnMessage.setBackground(new Color(255, 51, 51));
                    labelWarningData.setText("Digite a data de inicio e fim da pesquisa");
                    warningPanelData.setVisible(true);

                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAbrir = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnVisualizar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnFechar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnRelatorio = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        cardPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        warningPanelData = new javax.swing.JPanel();
        btnMessage = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningData = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        mGradientButton1 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        txtData1 = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtData2 = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        btnExit = new com.hq.swingmaterialdesign.materialdesign.MButton();
        tablePanel = new javax.swing.JScrollPane();
        tableAlunos = new javax.swing.JTable();
        formPanelAbrir = new javax.swing.JPanel();
        warningPanelForm = new javax.swing.JPanel();
        btnError = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningForm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mButton4 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botCancelar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botConfirmar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtSaldoInicial = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelDataAbertura = new javax.swing.JLabel();
        labelHorarioAbertura = new javax.swing.JLabel();
        labelFuncionario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        formPanelFechar = new javax.swing.JPanel();
        warningPanelForm1 = new javax.swing.JPanel();
        btnError1 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningForm1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mButton5 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botCancelarFechamento = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botConfirmarFechamento = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtSaldoFinal = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelDataFechamento = new javax.swing.JLabel();
        labelHorarioFechamento = new javax.swing.JLabel();
        labelFuncionarioFechamento = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        labelEntradas = new javax.swing.JLabel();
        labelSaidas = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelSaldoInicial = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bgMouseReleased(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(37, 46, 55));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAIXA");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 230, 40));

        btnAbrir.setBorder(null);
        btnAbrir.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrir.setText("Abrir");
        btnAbrir.setEndColor(new java.awt.Color(37, 46, 55));
        btnAbrir.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnAbrir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAbrir.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnAbrir.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnAbrir.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnAbrir.setStartColor(new java.awt.Color(37, 46, 55));
        btnAbrir.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        sidePanel.add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        btnVisualizar.setBorder(null);
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setText("vISUALIZAR");
        btnVisualizar.setEndColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnVisualizar.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnVisualizar.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnVisualizar.setStartColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        sidePanel.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        btnFechar.setBorder(null);
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("Fechar");
        btnFechar.setEndColor(new java.awt.Color(37, 46, 55));
        btnFechar.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnFechar.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnFechar.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnFechar.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnFechar.setStartColor(new java.awt.Color(37, 46, 55));
        btnFechar.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        sidePanel.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        btnRelatorio.setBorder(null);
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setText("GERAR RELATÓRIO");
        btnRelatorio.setEndColor(new java.awt.Color(37, 46, 55));
        btnRelatorio.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        btnRelatorio.setHoverEndColor(new java.awt.Color(37, 46, 55));
        btnRelatorio.setHoverStartColor(new java.awt.Color(0, 153, 153));
        btnRelatorio.setSelectedColor(new java.awt.Color(0, 153, 153));
        btnRelatorio.setStartColor(new java.awt.Color(37, 46, 55));
        btnRelatorio.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        sidePanel.add(btnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 230, 50));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 670));

        cardPanel.setLayout(new java.awt.CardLayout());

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelData.setBackground(new java.awt.Color(0, 153, 0));

        btnMessage.setBackground(new java.awt.Color(0, 153, 0));
        btnMessage.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnMessage.setBorderRadius(0);
        btnMessage.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnMessage.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageActionPerformed(evt);
            }
        });

        labelWarningData.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningData.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningData.setText("Cadastro efetuado com sucesso.");

        javax.swing.GroupLayout warningPanelDataLayout = new javax.swing.GroupLayout(warningPanelData);
        warningPanelData.setLayout(warningPanelDataLayout);
        warningPanelDataLayout.setHorizontalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelDataLayout.createSequentialGroup()
                .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelDataLayout.setVerticalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataPanel.add(warningPanelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        searchPanel.setBackground(new java.awt.Color(50, 60, 69));

        mGradientButton1.setForeground(new java.awt.Color(204, 204, 204));
        mGradientButton1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.SEARCH));
        mGradientButton1.setBorderRadius(58);
        mGradientButton1.setEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(26f));
        mGradientButton1.setHoverEndColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setHoverStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.setStartColor(new java.awt.Color(50, 60, 69));
        mGradientButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseExited(evt);
            }
        });
        mGradientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton1ActionPerformed(evt);
            }
        });

        txtData1.setBackground(new java.awt.Color(50, 60, 69));
        txtData1.setForeground(new java.awt.Color(240, 240, 240));
        txtData1.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtData1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData1.setLabel("Data Inicial");
        txtData1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtData1FocusGained(evt);
            }
        });

        txtData2.setBackground(new java.awt.Color(50, 60, 69));
        txtData2.setForeground(new java.awt.Color(240, 240, 240));
        txtData2.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtData2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData2.setLabel("Data Final");
        txtData2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtData2FocusGained(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        dataPanel.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 100));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(null);
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
        btnExit.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnExit.setBorderRadius(0);
        btnExit.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnExit.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        dataPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 50, 40));

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablePanel.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tablePanel.setHorizontalScrollBar(null);

        tableAlunos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableAlunos.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tableAlunos.setForeground(new java.awt.Color(72, 72, 72));
        tableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Funcionário", "Data", "Hora", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAlunos.setGridColor(new java.awt.Color(255, 255, 255));
        tableAlunos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableAlunos.setRowHeight(30);
        tableAlunos.setSelectionBackground(new java.awt.Color(205, 205, 205));
        tablePanel.setViewportView(tableAlunos);
        if (tableAlunos.getColumnModel().getColumnCount() > 0) {
            tableAlunos.getColumnModel().getColumn(0).setResizable(false);
            tableAlunos.getColumnModel().getColumn(1).setResizable(false);
            tableAlunos.getColumnModel().getColumn(2).setResizable(false);
            tableAlunos.getColumnModel().getColumn(3).setResizable(false);
            tableAlunos.getColumnModel().getColumn(4).setResizable(false);
        }
        tableAlunos.getTableHeader().setFont(new java.awt.Font("Nunito Bold", 0, 14));

        dataPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 670, 390));

        cardPanel.add(dataPanel, "card2");

        formPanelAbrir.setBackground(new java.awt.Color(255, 255, 255));
        formPanelAbrir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelForm.setBackground(new java.awt.Color(255, 51, 51));

        btnError.setBackground(new java.awt.Color(255, 51, 51));
        btnError.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnError.setBorderRadius(0);
        btnError.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnError.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorActionPerformed(evt);
            }
        });

        labelWarningForm.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningForm.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningForm.setText("Preencha os campos corretamente.");

        javax.swing.GroupLayout warningPanelFormLayout = new javax.swing.GroupLayout(warningPanelForm);
        warningPanelForm.setLayout(warningPanelFormLayout);
        warningPanelFormLayout.setHorizontalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelFormLayout.createSequentialGroup()
                .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelFormLayout.setVerticalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelAbrir.add(warningPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        mButton4.setBorder(null);
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
        mButton4.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton4.setBorderRadius(0);
        mButton4.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton4.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton4MouseExited(evt);
            }
        });
        mButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelAbrir.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        botCancelar.setBorder(null);
        botCancelar.setText("CANCELAR");
        botCancelar.setBorderRadius(50);
        botCancelar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botCancelar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        formPanelAbrir.add(botCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 514, 180, 50));

        botConfirmar.setBackground(new java.awt.Color(51, 51, 51));
        botConfirmar.setBorder(null);
        botConfirmar.setText("Confirmar");
        botConfirmar.setBorderRadius(50);
        botConfirmar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botConfirmar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConfirmarActionPerformed(evt);
            }
        });
        formPanelAbrir.add(botConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 514, 180, 50));

        txtSaldoInicial.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtSaldoInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtSaldoInicial.setLabel("Saldo inicial");
        txtSaldoInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSaldoInicialFocusGained(evt);
            }
        });
        formPanelAbrir.add(txtSaldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 330, 50));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel2.setText("Data");
        formPanelAbrir.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel3.setText("Horário de abertura");
        formPanelAbrir.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setText("Funcionário");
        formPanelAbrir.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        labelDataAbertura.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelDataAbertura.setText("jLabel5");
        formPanelAbrir.add(labelDataAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 210, 130, -1));

        labelHorarioAbertura.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelHorarioAbertura.setText("jLabel6");
        formPanelAbrir.add(labelHorarioAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 260, 120, -1));

        labelFuncionario.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelFuncionario.setText("jLabel7");
        formPanelAbrir.add(labelFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 310, 180, -1));
        formPanelAbrir.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 330, -1));
        formPanelAbrir.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 330, 10));
        formPanelAbrir.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 330, 10));

        cardPanel.add(formPanelAbrir, "card3");

        formPanelFechar.setBackground(new java.awt.Color(255, 255, 255));
        formPanelFechar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelForm1.setBackground(new java.awt.Color(255, 51, 51));

        btnError1.setBackground(new java.awt.Color(255, 51, 51));
        btnError1.setBorder(null);
        btnError1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnError1.setBorderRadius(0);
        btnError1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnError1.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnError1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnError1ActionPerformed(evt);
            }
        });

        labelWarningForm1.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningForm1.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningForm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningForm1.setText("Preencha os campos corretamente.");

        javax.swing.GroupLayout warningPanelForm1Layout = new javax.swing.GroupLayout(warningPanelForm1);
        warningPanelForm1.setLayout(warningPanelForm1Layout);
        warningPanelForm1Layout.setHorizontalGroup(
            warningPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelForm1Layout.createSequentialGroup()
                .addComponent(labelWarningForm1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnError1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelForm1Layout.setVerticalGroup(
            warningPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningForm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnError1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelFechar.add(warningPanelForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        mButton5.setBorder(null);
        mButton5.setForeground(new java.awt.Color(153, 153, 153));
        mButton5.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton5.setBorderRadius(0);
        mButton5.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton5.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton5MouseExited(evt);
            }
        });
        mButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanelFechar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        botCancelarFechamento.setBorder(null);
        botCancelarFechamento.setText("CANCELAR");
        botCancelarFechamento.setBorderRadius(50);
        botCancelarFechamento.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botCancelarFechamento.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelarFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarFechamentoActionPerformed(evt);
            }
        });
        formPanelFechar.add(botCancelarFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 514, 180, 50));

        botConfirmarFechamento.setBackground(new java.awt.Color(51, 51, 51));
        botConfirmarFechamento.setBorder(null);
        botConfirmarFechamento.setText("Confirmar");
        botConfirmarFechamento.setBorderRadius(50);
        botConfirmarFechamento.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botConfirmarFechamento.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botConfirmarFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConfirmarFechamentoActionPerformed(evt);
            }
        });
        formPanelFechar.add(botConfirmarFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 514, 180, 50));

        txtSaldoFinal.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtSaldoFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtSaldoFinal.setLabel("Saldo final");
        txtSaldoFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSaldoFinalFocusGained(evt);
            }
        });
        formPanelFechar.add(txtSaldoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 280, 50));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel5.setText("Data");
        formPanelFechar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel6.setText("Horário");
        formPanelFechar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel7.setText("Funcionário");
        formPanelFechar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        labelDataFechamento.setText("jLabel5");
        formPanelFechar.add(labelDataFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 210, 130, -1));

        labelHorarioFechamento.setText("jLabel6");
        formPanelFechar.add(labelHorarioFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 260, 190, -1));

        labelFuncionarioFechamento.setText("jLabel7");
        formPanelFechar.add(labelFuncionarioFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 310, 180, -1));
        formPanelFechar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 280, -1));
        formPanelFechar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 280, 10));
        formPanelFechar.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 280, 10));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel8.setText("Entradas");
        formPanelFechar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel9.setText("Saídas");
        formPanelFechar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));
        formPanelFechar.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 280, 10));
        formPanelFechar.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 280, 10));

        labelEntradas.setText("jLabel10");
        formPanelFechar.add(labelEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        labelSaidas.setText("jLabel10");
        formPanelFechar.add(labelSaidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel10.setText("Saldo Inicial");
        formPanelFechar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        labelSaldoInicial.setText("jLabel5");
        formPanelFechar.add(labelSaldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 130, -1));
        formPanelFechar.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 280, -1));

        cardPanel.add(formPanelFechar, "card4");

        bg.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 710, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseEntered
        mButton4.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_mButton4MouseEntered

    private void mButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseExited
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_mButton4MouseExited

    private void mButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton4ActionPerformed
    private void voltar() {
        menuSelection = 0;
        btnAbrir.unselect();;
        btnFechar.unselect();;
        btnVisualizar.unselect();
        limparCampos();
        makeAllBlack();
        dataPanel.setVisible(true);
        formPanelAbrir.setVisible(false);
        formPanelFechar.setVisible(false);
        btnRelatorio.unselect();
        atualizaTabela();
    }
    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        System.out.println("idjfd");
        if (menuSelection == 0) {

            if (ControleCaixa.getCaixa() == null) {
                menuSelection = 1;
                p = new Caixa();
                labelDataAbertura.setText(Conversoes.getDateFormatedToString(new Date()));
                labelHorarioAbertura.setText(Conversoes.getStringOfTime(new Date()));
                labelFuncionario.setText(ControleSecretario.getLogado().getNome());
                this.repaint();
                dataPanel.setVisible(false);
                formPanelAbrir.setVisible(true);
                selecionado = null;
            } else {
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                labelWarningData.setText("Já há um caixa aberto");
                warningPanelData.setVisible(true);
                btnAbrir.unselect();
                menuSelection = 0;
            }

        } else {
            if (menuSelection == 2) {
                btnFechar.select();
                btnAbrir.unselect();
            } else if (menuSelection == 3) {
                btnVisualizar.select();
                btnAbrir.unselect();
            } else if (menuSelection == 4) {
                btnRelatorio.select();
                btnAbrir.unselect();
            }
        }


    }//GEN-LAST:event_btnAbrirActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed

        warningPanelData.setVisible(false);
        warningPanelForm.setVisible(false);
        voltar();
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConfirmarActionPerformed

        boolean flag = false;
        String message = "";

        if (txtSaldoInicial.getText().equals("")) {
            txtSaldoInicial.setForeground(errorColor);
            flag = true;
        }

        this.repaint();

        if (flag) {
            message = "Preencha todos os campos corretamente.";

        }

        if (!flag) {

            p.setData(new Date());
            p.setEntradas(0.0);
            p.setSaidas(0.0);
            p.setHrAbertura(new Date());
            p.setHrFechamento(null);
            p.setSaldoFinal(null);
            p.setSaldoInicial(Double.parseDouble(txtSaldoInicial.getText().replace(',', '.')));

            p.setSecretario(ControleSecretario.getLogado());

            contCaixa.persist(p);

            ControleCaixa.setCaixa(p);

            System.out.println(p.toString());
            message = "Cadastro efetuado com sucesso.";
            warningPanelData.setBackground(new Color(0, 153, 0));
            btnMessage.setBackground(new Color(0, 153, 0));
            labelWarningData.setText(message);
            warningPanelData.setVisible(true);
            voltar();

        } else {

            labelWarningForm.setText(message);
            warningPanelForm.setVisible(true);
            warningPanelForm.setBackground(new Color(255, 51, 51));
            btnError.setBackground(new Color(255, 51, 51));

        }
    }//GEN-LAST:event_botConfirmarActionPerformed

    private void makeAllBlack() {
        txtSaldoInicial.setForeground(Color.black);
        txtSaldoFinal.setForeground(Color.black);

    }

    private void limparCampos() {
        txtSaldoInicial.setText("");
        labelDataAbertura.setText("");
        labelFuncionario.setText("");
        labelHorarioAbertura.setText("");
    }
    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        if (menuSelection == 0) {
            int linha = tableAlunos.getSelectedRow();
            int codigo;
            if (linha != -1) {
                menuSelection = 3;
                int colunas = tableAlunos.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableAlunos.getColumnName(x).equals("Código")) {
                        codigo = (int) tableAlunos.getValueAt(linha, x);
                        selecionado = contCaixa.findByCodigo(codigo);
                        setCaixa();
                        dataPanel.setVisible(false);
                        formPanelAbrir.setVisible(true);
                    }
                }

            } else {

                labelWarningData.setText("Selecione um caixa.");
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                warningPanelData.setVisible(true);
                voltar();
                //timer
            }
        } else {
            if (menuSelection == 1) {
                btnAbrir.select();
                btnVisualizar.unselect();
            } else if (menuSelection == 2) {
                btnFechar.select();
                btnVisualizar.unselect();
            } else if (menuSelection == 4) {
                btnRelatorio.select();
                btnVisualizar.unselect();
            }
        }

    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void mGradientButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton1ActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_mGradientButton1ActionPerformed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseReleased
        try {
            setOpacity((float) 1);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseReleased

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
        try {
            setOpacity((float) 0.9);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseDragged

    private void mGradientButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseEntered
        mGradientButton1.setForeground(Color.white);
    }//GEN-LAST:event_mGradientButton1MouseEntered

    private void mGradientButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseExited
        mGradientButton1.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_mGradientButton1MouseExited

    private void btnErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorActionPerformed
        warningPanelForm.setVisible(false);
    }//GEN-LAST:event_btnErrorActionPerformed

    private void btnMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageActionPerformed
        warningPanelData.setVisible(false);
    }//GEN-LAST:event_btnMessageActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

        if (menuSelection == 0) {
            if (ControleCaixa.getCaixa() != null) {

                menuSelection = 2;
                dataPanel.setVisible(false);
                formPanelFechar.setVisible(true);
                selecionado = ControleCaixa.getCaixa();
                setCaixa();
            } else {
                labelWarningData.setText("Não há caixa aberto");
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                voltar();
            }
        } else {
            if (menuSelection == 1) {
                btnAbrir.select();
                btnFechar.unselect();
            } else if (menuSelection == 3) {
                btnVisualizar.select();
                btnFechar.unselect();
            } else if (menuSelection == 4) {
                btnRelatorio.select();
                btnFechar.unselect();
            }
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtSaldoInicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaldoInicialFocusGained
        txtSaldoInicial.setForeground(Color.black);

    }//GEN-LAST:event_txtSaldoInicialFocusGained

    private void btnError1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnError1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnError1ActionPerformed

    private void mButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mButton5MouseEntered

    private void mButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_mButton5MouseExited

    private void mButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_mButton5ActionPerformed

    private void botCancelarFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarFechamentoActionPerformed

        warningPanelData.setVisible(false);
        warningPanelForm1.setVisible(false);
        voltar();
    }//GEN-LAST:event_botCancelarFechamentoActionPerformed

    private void botConfirmarFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConfirmarFechamentoActionPerformed

        boolean flag = false;
        String message = "";

        if (txtSaldoFinal.getText().equals("")) {
            txtSaldoFinal.setForeground(errorColor);
            flag = true;
        }

        this.repaint();
        if (flag) {
            message = "Preencha todos os campos corretamente.";
        }
        if (!flag) {

            p.setSaldoFinal(Double.parseDouble(txtSaldoFinal.getText().replace(',', '.')));
            p.setHrFechamento(new Date());
            contCaixa.alter(p);

            ControleCaixa.setCaixa(null);

            System.out.println(p.toString());
            message = "Cadastro efetuado com sucesso.";
            voltar();
            warningPanelData.setBackground(new Color(0, 153, 0));
            btnMessage.setBackground(new Color(0, 153, 0));
            labelWarningData.setText(message);
            warningPanelData.setVisible(true);

        } else {

            labelWarningForm.setText(message);
            warningPanelForm.setVisible(true);
            warningPanelForm.setBackground(new Color(255, 51, 51));
            btnError.setBackground(new Color(255, 51, 51));

        }
    }//GEN-LAST:event_botConfirmarFechamentoActionPerformed

    private void txtSaldoFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaldoFinalFocusGained
        txtSaldoFinal.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtSaldoFinalFocusGained

    private void txtData1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtData1FocusGained
        txtData1.setForeground(branco);
        if (txtData1.getText().equals("  /  /    "))
            txtData1.setCaretPosition(0);
    }//GEN-LAST:event_txtData1FocusGained

    private void txtData2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtData2FocusGained
        txtData2.setForeground(branco);
        if (txtData2.getText().equals("  /  /    "))
            txtData2.setCaretPosition(0);
    }//GEN-LAST:event_txtData2FocusGained

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        if (menuSelection == 0) {

            if (!txtData1.getText().equals("  /  /    ") && !txtData2.getText().equals("  /  /    ")) {
                menuSelection = 3;
                HashMap<String, Object> parametros = new HashMap();
                parametros.put("logo", "src/view/images/favicon2.png");
                parametros.put("funcionario", ControleSecretario.getLogado().getNome());
                parametros.put("data1", txtData1.getText());
                parametros.put("data2", txtData2.getText());
                contCaixa.gerarRelatorio(parametros, contCaixa.findByDatas(txtData1.getText(), txtData2.getText()), "src/relatorios/Balanco.jrxml");

            } else {

                labelWarningData.setText("Digite um período de datas.");
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                warningPanelData.setVisible(true);
                voltar();
                //timer
            }
        } else {
            if (menuSelection == 1) {
                btnAbrir.select();
                btnRelatorio.unselect();
            } else if (menuSelection == 2) {
                btnFechar.select();
                btnRelatorio.unselect();
            } else if (menuSelection == 3) {
                btnVisualizar.select();
                btnRelatorio.unselect();
            }
        }

    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void setCaixa() {
        p = ControleCaixa.getCaixa();
        p = contCaixa.findByCodigo(p.getCodigo());
        labelSaldoInicial.setText(Double.toString(selecionado.getSaldoInicial()));
        labelEntradas.setText(Double.toString(selecionado.getEntradas()));
        labelSaidas.setText(Double.toString(selecionado.getSaidas()));
        labelHorarioFechamento.setText(Conversoes.getStringOfTime(selecionado.getHrAbertura()) + "-" + Conversoes.getStringOfTime(new Date()));
        labelHorarioFechamento.setText(Conversoes.getStringOfTime(new Date()));
        labelDataFechamento.setText(Conversoes.getDateFormatedToString(selecionado.getData()));
        labelFuncionarioFechamento.setText(selecionado.getSecretario().getNome());
        labelFuncionario.setText(selecionado.getSecretario().getNome());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCaixa dialog = new FormCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelar;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelarFechamento;
    private com.hq.swingmaterialdesign.materialdesign.MButton botConfirmar;
    private com.hq.swingmaterialdesign.materialdesign.MButton botConfirmarFechamento;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnAbrir;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnError;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnError1;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnExit;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnFechar;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnMessage;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnRelatorio;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnVisualizar;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel formPanelAbrir;
    private javax.swing.JPanel formPanelFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labelDataAbertura;
    private javax.swing.JLabel labelDataFechamento;
    private javax.swing.JLabel labelEntradas;
    private javax.swing.JLabel labelFuncionario;
    private javax.swing.JLabel labelFuncionarioFechamento;
    private javax.swing.JLabel labelHorarioAbertura;
    private javax.swing.JLabel labelHorarioFechamento;
    private javax.swing.JLabel labelSaidas;
    private javax.swing.JLabel labelSaldoInicial;
    private javax.swing.JLabel labelWarningData;
    private javax.swing.JLabel labelWarningForm;
    private javax.swing.JLabel labelWarningForm1;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton4;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton5;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tableAlunos;
    private javax.swing.JScrollPane tablePanel;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtData1;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtData2;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtSaldoFinal;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtSaldoInicial;
    private javax.swing.JPanel warningPanelData;
    private javax.swing.JPanel warningPanelForm;
    private javax.swing.JPanel warningPanelForm1;
    // End of variables declaration//GEN-END:variables
}
